// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Definitions.proto
// Protobuf C++ Version: 6.31.1

#ifndef Definitions_2eproto_2epb_2eh
#define Definitions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "Spaces.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Definitions_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_Definitions_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Definitions_2eproto;
}  // extern "C"
namespace Schola {
class AgentDefinition;
struct AgentDefinitionDefaultTypeInternal;
SCHOLAPROTOBUF_API extern AgentDefinitionDefaultTypeInternal _AgentDefinition_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull AgentDefinition_class_data_;
class EnvironmentDefinition;
struct EnvironmentDefinitionDefaultTypeInternal;
SCHOLAPROTOBUF_API extern EnvironmentDefinitionDefaultTypeInternal _EnvironmentDefinition_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull EnvironmentDefinition_class_data_;
class EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse;
struct EnvironmentDefinition_AgentDefinitionsEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern EnvironmentDefinition_AgentDefinitionsEntry_DoNotUseDefaultTypeInternal _EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse_class_data_;
class TrainingDefinition;
struct TrainingDefinitionDefaultTypeInternal;
SCHOLAPROTOBUF_API extern TrainingDefinitionDefaultTypeInternal _TrainingDefinition_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull TrainingDefinition_class_data_;
}  // namespace Schola
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Schola {

// ===================================================================


// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API AgentDefinition final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.AgentDefinition) */ {
 public:
  inline AgentDefinition() : AgentDefinition(nullptr) {}
  ~AgentDefinition() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AgentDefinition* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AgentDefinition));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AgentDefinition(::google::protobuf::internal::ConstantInitialized);

  inline AgentDefinition(const AgentDefinition& from) : AgentDefinition(nullptr, from) {}
  inline AgentDefinition(AgentDefinition&& from) noexcept
      : AgentDefinition(nullptr, ::std::move(from)) {}
  inline AgentDefinition& operator=(const AgentDefinition& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentDefinition& operator=(AgentDefinition&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentDefinition& default_instance() {
    return *reinterpret_cast<const AgentDefinition*>(
        &_AgentDefinition_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AgentDefinition& a, AgentDefinition& b) { a.Swap(&b); }
  inline void Swap(AgentDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentDefinition* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AgentDefinition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AgentDefinition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AgentDefinition& from) { AgentDefinition::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AgentDefinition* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.AgentDefinition"; }

 protected:
  explicit AgentDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AgentDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AgentDefinition& from);
  AgentDefinition(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AgentDefinition&& from) noexcept
      : AgentDefinition(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAgentTypeFieldNumber = 3,
    kObsSpaceFieldNumber = 1,
    kActionSpaceFieldNumber = 2,
  };
  // string agent_type = 3;
  void clear_agent_type() ;
  const ::std::string& agent_type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_agent_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_agent_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_agent_type();
  void set_allocated_agent_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_agent_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_agent_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_agent_type();

  public:
  // .Schola.Space obs_space = 1;
  bool has_obs_space() const;
  void clear_obs_space() ;
  const ::Schola::Space& obs_space() const;
  [[nodiscard]] ::Schola::Space* PROTOBUF_NULLABLE release_obs_space();
  ::Schola::Space* PROTOBUF_NONNULL mutable_obs_space();
  void set_allocated_obs_space(::Schola::Space* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_obs_space(::Schola::Space* PROTOBUF_NULLABLE value);
  ::Schola::Space* PROTOBUF_NULLABLE unsafe_arena_release_obs_space();

  private:
  const ::Schola::Space& _internal_obs_space() const;
  ::Schola::Space* PROTOBUF_NONNULL _internal_mutable_obs_space();

  public:
  // .Schola.Space action_space = 2;
  bool has_action_space() const;
  void clear_action_space() ;
  const ::Schola::Space& action_space() const;
  [[nodiscard]] ::Schola::Space* PROTOBUF_NULLABLE release_action_space();
  ::Schola::Space* PROTOBUF_NONNULL mutable_action_space();
  void set_allocated_action_space(::Schola::Space* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_action_space(::Schola::Space* PROTOBUF_NULLABLE value);
  ::Schola::Space* PROTOBUF_NULLABLE unsafe_arena_release_action_space();

  private:
  const ::Schola::Space& _internal_action_space() const;
  ::Schola::Space* PROTOBUF_NONNULL _internal_mutable_action_space();

  public:
  // @@protoc_insertion_point(class_scope:Schola.AgentDefinition)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AgentDefinition& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr agent_type_;
    ::Schola::Space* PROTOBUF_NULLABLE obs_space_;
    ::Schola::Space* PROTOBUF_NULLABLE action_space_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Definitions_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull AgentDefinition_class_data_;
// -------------------------------------------------------------------

class EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_Definitions_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 62,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API EnvironmentDefinition final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.EnvironmentDefinition) */ {
 public:
  inline EnvironmentDefinition() : EnvironmentDefinition(nullptr) {}
  ~EnvironmentDefinition() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnvironmentDefinition* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnvironmentDefinition));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnvironmentDefinition(::google::protobuf::internal::ConstantInitialized);

  inline EnvironmentDefinition(const EnvironmentDefinition& from) : EnvironmentDefinition(nullptr, from) {}
  inline EnvironmentDefinition(EnvironmentDefinition&& from) noexcept
      : EnvironmentDefinition(nullptr, ::std::move(from)) {}
  inline EnvironmentDefinition& operator=(const EnvironmentDefinition& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnvironmentDefinition& operator=(EnvironmentDefinition&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnvironmentDefinition& default_instance() {
    return *reinterpret_cast<const EnvironmentDefinition*>(
        &_EnvironmentDefinition_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(EnvironmentDefinition& a, EnvironmentDefinition& b) { a.Swap(&b); }
  inline void Swap(EnvironmentDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnvironmentDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnvironmentDefinition* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnvironmentDefinition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnvironmentDefinition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnvironmentDefinition& from) { EnvironmentDefinition::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnvironmentDefinition* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.EnvironmentDefinition"; }

 protected:
  explicit EnvironmentDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EnvironmentDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EnvironmentDefinition& from);
  EnvironmentDefinition(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EnvironmentDefinition&& from) noexcept
      : EnvironmentDefinition(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAgentDefinitionsFieldNumber = 1,
  };
  // map<string, .Schola.AgentDefinition> agent_definitions = 1;
  int agent_definitions_size() const;
  private:
  int _internal_agent_definitions_size() const;

  public:
  void clear_agent_definitions() ;
  const ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>& agent_definitions() const;
  ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>* PROTOBUF_NONNULL mutable_agent_definitions();

  private:
  const ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>& _internal_agent_definitions() const;
  ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>* PROTOBUF_NONNULL _internal_mutable_agent_definitions();

  public:
  // @@protoc_insertion_point(class_scope:Schola.EnvironmentDefinition)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EnvironmentDefinition& from_msg);
    ::google::protobuf::internal::MapField<EnvironmentDefinition_AgentDefinitionsEntry_DoNotUse, std::string, ::Schola::AgentDefinition,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        agent_definitions_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Definitions_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull EnvironmentDefinition_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API TrainingDefinition final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.TrainingDefinition) */ {
 public:
  inline TrainingDefinition() : TrainingDefinition(nullptr) {}
  ~TrainingDefinition() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainingDefinition* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainingDefinition));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrainingDefinition(::google::protobuf::internal::ConstantInitialized);

  inline TrainingDefinition(const TrainingDefinition& from) : TrainingDefinition(nullptr, from) {}
  inline TrainingDefinition(TrainingDefinition&& from) noexcept
      : TrainingDefinition(nullptr, ::std::move(from)) {}
  inline TrainingDefinition& operator=(const TrainingDefinition& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainingDefinition& operator=(TrainingDefinition&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainingDefinition& default_instance() {
    return *reinterpret_cast<const TrainingDefinition*>(
        &_TrainingDefinition_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TrainingDefinition& a, TrainingDefinition& b) { a.Swap(&b); }
  inline void Swap(TrainingDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainingDefinition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainingDefinition* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrainingDefinition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrainingDefinition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrainingDefinition& from) { TrainingDefinition::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrainingDefinition* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.TrainingDefinition"; }

 protected:
  explicit TrainingDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrainingDefinition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrainingDefinition& from);
  TrainingDefinition(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrainingDefinition&& from) noexcept
      : TrainingDefinition(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnvironmentDefinitionsFieldNumber = 1,
  };
  // repeated .Schola.EnvironmentDefinition environment_definitions = 1;
  int environment_definitions_size() const;
  private:
  int _internal_environment_definitions_size() const;

  public:
  void clear_environment_definitions() ;
  ::Schola::EnvironmentDefinition* PROTOBUF_NONNULL mutable_environment_definitions(int index);
  ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>* PROTOBUF_NONNULL mutable_environment_definitions();

  private:
  const ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>& _internal_environment_definitions() const;
  ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>* PROTOBUF_NONNULL _internal_mutable_environment_definitions();
  public:
  const ::Schola::EnvironmentDefinition& environment_definitions(int index) const;
  ::Schola::EnvironmentDefinition* PROTOBUF_NONNULL add_environment_definitions();
  const ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>& environment_definitions() const;
  // @@protoc_insertion_point(class_scope:Schola.TrainingDefinition)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrainingDefinition& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Schola::EnvironmentDefinition > environment_definitions_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Definitions_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull TrainingDefinition_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AgentDefinition

// .Schola.Space obs_space = 1;
inline bool AgentDefinition::has_obs_space() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.obs_space_ != nullptr);
  return value;
}
inline const ::Schola::Space& AgentDefinition::_internal_obs_space() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Schola::Space* p = _impl_.obs_space_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Space&>(::Schola::_Space_default_instance_);
}
inline const ::Schola::Space& AgentDefinition::obs_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.AgentDefinition.obs_space)
  return _internal_obs_space();
}
inline void AgentDefinition::unsafe_arena_set_allocated_obs_space(
    ::Schola::Space* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.obs_space_);
  }
  _impl_.obs_space_ = reinterpret_cast<::Schola::Space*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.AgentDefinition.obs_space)
}
inline ::Schola::Space* PROTOBUF_NULLABLE AgentDefinition::release_obs_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Schola::Space* released = _impl_.obs_space_;
  _impl_.obs_space_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Schola::Space* PROTOBUF_NULLABLE AgentDefinition::unsafe_arena_release_obs_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Schola.AgentDefinition.obs_space)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Schola::Space* temp = _impl_.obs_space_;
  _impl_.obs_space_ = nullptr;
  return temp;
}
inline ::Schola::Space* PROTOBUF_NONNULL AgentDefinition::_internal_mutable_obs_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.obs_space_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Schola::Space>(GetArena());
    _impl_.obs_space_ = reinterpret_cast<::Schola::Space*>(p);
  }
  return _impl_.obs_space_;
}
inline ::Schola::Space* PROTOBUF_NONNULL AgentDefinition::mutable_obs_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Schola::Space* _msg = _internal_mutable_obs_space();
  // @@protoc_insertion_point(field_mutable:Schola.AgentDefinition.obs_space)
  return _msg;
}
inline void AgentDefinition::set_allocated_obs_space(::Schola::Space* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.obs_space_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.obs_space_ = reinterpret_cast<::Schola::Space*>(value);
  // @@protoc_insertion_point(field_set_allocated:Schola.AgentDefinition.obs_space)
}

// .Schola.Space action_space = 2;
inline bool AgentDefinition::has_action_space() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.action_space_ != nullptr);
  return value;
}
inline const ::Schola::Space& AgentDefinition::_internal_action_space() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Schola::Space* p = _impl_.action_space_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Space&>(::Schola::_Space_default_instance_);
}
inline const ::Schola::Space& AgentDefinition::action_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.AgentDefinition.action_space)
  return _internal_action_space();
}
inline void AgentDefinition::unsafe_arena_set_allocated_action_space(
    ::Schola::Space* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_space_);
  }
  _impl_.action_space_ = reinterpret_cast<::Schola::Space*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.AgentDefinition.action_space)
}
inline ::Schola::Space* PROTOBUF_NULLABLE AgentDefinition::release_action_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Schola::Space* released = _impl_.action_space_;
  _impl_.action_space_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Schola::Space* PROTOBUF_NULLABLE AgentDefinition::unsafe_arena_release_action_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Schola.AgentDefinition.action_space)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Schola::Space* temp = _impl_.action_space_;
  _impl_.action_space_ = nullptr;
  return temp;
}
inline ::Schola::Space* PROTOBUF_NONNULL AgentDefinition::_internal_mutable_action_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.action_space_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Schola::Space>(GetArena());
    _impl_.action_space_ = reinterpret_cast<::Schola::Space*>(p);
  }
  return _impl_.action_space_;
}
inline ::Schola::Space* PROTOBUF_NONNULL AgentDefinition::mutable_action_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::Schola::Space* _msg = _internal_mutable_action_space();
  // @@protoc_insertion_point(field_mutable:Schola.AgentDefinition.action_space)
  return _msg;
}
inline void AgentDefinition::set_allocated_action_space(::Schola::Space* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_space_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.action_space_ = reinterpret_cast<::Schola::Space*>(value);
  // @@protoc_insertion_point(field_set_allocated:Schola.AgentDefinition.action_space)
}

// string agent_type = 3;
inline void AgentDefinition::clear_agent_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agent_type_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& AgentDefinition::agent_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.AgentDefinition.agent_type)
  return _internal_agent_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AgentDefinition::set_agent_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.agent_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Schola.AgentDefinition.agent_type)
}
inline ::std::string* PROTOBUF_NONNULL AgentDefinition::mutable_agent_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_agent_type();
  // @@protoc_insertion_point(field_mutable:Schola.AgentDefinition.agent_type)
  return _s;
}
inline const ::std::string& AgentDefinition::_internal_agent_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.agent_type_.Get();
}
inline void AgentDefinition::_internal_set_agent_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.agent_type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AgentDefinition::_internal_mutable_agent_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.agent_type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AgentDefinition::release_agent_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Schola.AgentDefinition.agent_type)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.agent_type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.agent_type_.Set("", GetArena());
  }
  return released;
}
inline void AgentDefinition::set_allocated_agent_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.agent_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.agent_type_.IsDefault()) {
    _impl_.agent_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.AgentDefinition.agent_type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// EnvironmentDefinition

// map<string, .Schola.AgentDefinition> agent_definitions = 1;
inline int EnvironmentDefinition::_internal_agent_definitions_size() const {
  return _internal_agent_definitions().size();
}
inline int EnvironmentDefinition::agent_definitions_size() const {
  return _internal_agent_definitions_size();
}
inline void EnvironmentDefinition::clear_agent_definitions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agent_definitions_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>& EnvironmentDefinition::_internal_agent_definitions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.agent_definitions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>& EnvironmentDefinition::agent_definitions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Schola.EnvironmentDefinition.agent_definitions)
  return _internal_agent_definitions();
}
inline ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>* PROTOBUF_NONNULL EnvironmentDefinition::_internal_mutable_agent_definitions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.agent_definitions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::Schola::AgentDefinition>* PROTOBUF_NONNULL EnvironmentDefinition::mutable_agent_definitions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Schola.EnvironmentDefinition.agent_definitions)
  return _internal_mutable_agent_definitions();
}

// -------------------------------------------------------------------

// TrainingDefinition

// repeated .Schola.EnvironmentDefinition environment_definitions = 1;
inline int TrainingDefinition::_internal_environment_definitions_size() const {
  return _internal_environment_definitions().size();
}
inline int TrainingDefinition::environment_definitions_size() const {
  return _internal_environment_definitions_size();
}
inline void TrainingDefinition::clear_environment_definitions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_definitions_.Clear();
}
inline ::Schola::EnvironmentDefinition* PROTOBUF_NONNULL TrainingDefinition::mutable_environment_definitions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Schola.TrainingDefinition.environment_definitions)
  return _internal_mutable_environment_definitions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>* PROTOBUF_NONNULL TrainingDefinition::mutable_environment_definitions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.TrainingDefinition.environment_definitions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_environment_definitions();
}
inline const ::Schola::EnvironmentDefinition& TrainingDefinition::environment_definitions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.TrainingDefinition.environment_definitions)
  return _internal_environment_definitions().Get(index);
}
inline ::Schola::EnvironmentDefinition* PROTOBUF_NONNULL TrainingDefinition::add_environment_definitions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Schola::EnvironmentDefinition* _add = _internal_mutable_environment_definitions()->Add();
  // @@protoc_insertion_point(field_add:Schola.TrainingDefinition.environment_definitions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>& TrainingDefinition::environment_definitions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.TrainingDefinition.environment_definitions)
  return _internal_environment_definitions();
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>&
TrainingDefinition::_internal_environment_definitions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.environment_definitions_;
}
inline ::google::protobuf::RepeatedPtrField<::Schola::EnvironmentDefinition>* PROTOBUF_NONNULL
TrainingDefinition::_internal_mutable_environment_definitions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.environment_definitions_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // Definitions_2eproto_2epb_2eh
