// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DType.proto
// Protobuf C++ Version: 6.31.1

#ifndef DType_2eproto_2epb_2eh
#define DType_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DType_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_DType_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_DType_2eproto;
}  // extern "C"
namespace Schola {
enum DType : int;
SCHOLAPROTOBUF_API extern const uint32_t DType_internal_data_[];
}  // namespace Schola
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Schola::DType_internal_data_>
    internal::EnumTraitsImpl::value<::Schola::DType>;
}  // namespace protobuf
}  // namespace google

namespace Schola {
enum DType : int {
  FLOAT32 = 0,
  UINT8 = 1,
  UINT16 = 2,
  UINT32 = 3,
  UINT64 = 4,
  INT8 = 5,
  INT16 = 6,
  INT32 = 7,
  INT64 = 8,
  FLOAT16 = 9,
  FLOAT64 = 10,
  BOOL = 11,
  DType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  DType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

SCHOLAPROTOBUF_API extern const uint32_t DType_internal_data_[];
inline constexpr DType DType_MIN =
    static_cast<DType>(0);
inline constexpr DType DType_MAX =
    static_cast<DType>(11);
inline bool DType_IsValid(int value) {
  return 0 <= value && value <= 11;
}
inline constexpr int DType_ARRAYSIZE = 11 + 1;
SCHOLAPROTOBUF_API const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DType_descriptor();
template <typename T>
const ::std::string& DType_Name(T value) {
  static_assert(::std::is_same<T, DType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to DType_Name().");
  return DType_Name(static_cast<DType>(value));
}
template <>
inline const ::std::string& DType_Name(DType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DType_descriptor, 0, 11>(
      static_cast<int>(value));
}
inline bool DType_Parse(
    ::absl::string_view name, DType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<DType>(DType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Schola::DType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Schola::DType>() {
  return ::Schola::DType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // DType_2eproto_2epb_2eh
