// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GymConnector.proto
// Protobuf C++ Version: 6.31.1

#ifndef GymConnector_2eproto_2epb_2eh
#define GymConnector_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "Definitions.pb.h"
#include "State.pb.h"
#include "StateUpdates.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_GymConnector_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_GymConnector_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_GymConnector_2eproto;
}  // extern "C"
namespace Schola {
enum AutoResetType : int;
SCHOLAPROTOBUF_API extern const uint32_t AutoResetType_internal_data_[];
class GymConnectorStartRequest;
struct GymConnectorStartRequestDefaultTypeInternal;
SCHOLAPROTOBUF_API extern GymConnectorStartRequestDefaultTypeInternal _GymConnectorStartRequest_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull GymConnectorStartRequest_class_data_;
class GymConnectorStartResponse;
struct GymConnectorStartResponseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern GymConnectorStartResponseDefaultTypeInternal _GymConnectorStartResponse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull GymConnectorStartResponse_class_data_;
class InitialStateRequest;
struct InitialStateRequestDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialStateRequestDefaultTypeInternal _InitialStateRequest_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull InitialStateRequest_class_data_;
class TrainingDefinitionRequest;
struct TrainingDefinitionRequestDefaultTypeInternal;
SCHOLAPROTOBUF_API extern TrainingDefinitionRequestDefaultTypeInternal _TrainingDefinitionRequest_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull TrainingDefinitionRequest_class_data_;
}  // namespace Schola
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Schola::AutoResetType_internal_data_>
    internal::EnumTraitsImpl::value<::Schola::AutoResetType>;
}  // namespace protobuf
}  // namespace google

namespace Schola {
enum AutoResetType : int {
  SAME_STEP = 0,
  NEXT_STEP = 1,
  DISABLED = 2,
  AutoResetType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  AutoResetType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

SCHOLAPROTOBUF_API extern const uint32_t AutoResetType_internal_data_[];
inline constexpr AutoResetType AutoResetType_MIN =
    static_cast<AutoResetType>(0);
inline constexpr AutoResetType AutoResetType_MAX =
    static_cast<AutoResetType>(2);
inline bool AutoResetType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int AutoResetType_ARRAYSIZE = 2 + 1;
SCHOLAPROTOBUF_API const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AutoResetType_descriptor();
template <typename T>
const ::std::string& AutoResetType_Name(T value) {
  static_assert(::std::is_same<T, AutoResetType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to AutoResetType_Name().");
  return AutoResetType_Name(static_cast<AutoResetType>(value));
}
template <>
inline const ::std::string& AutoResetType_Name(AutoResetType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AutoResetType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool AutoResetType_Parse(
    ::absl::string_view name, AutoResetType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AutoResetType>(AutoResetType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API TrainingDefinitionRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Schola.TrainingDefinitionRequest) */ {
 public:
  inline TrainingDefinitionRequest() : TrainingDefinitionRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainingDefinitionRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainingDefinitionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrainingDefinitionRequest(::google::protobuf::internal::ConstantInitialized);

  inline TrainingDefinitionRequest(const TrainingDefinitionRequest& from) : TrainingDefinitionRequest(nullptr, from) {}
  inline TrainingDefinitionRequest(TrainingDefinitionRequest&& from) noexcept
      : TrainingDefinitionRequest(nullptr, ::std::move(from)) {}
  inline TrainingDefinitionRequest& operator=(const TrainingDefinitionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainingDefinitionRequest& operator=(TrainingDefinitionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainingDefinitionRequest& default_instance() {
    return *reinterpret_cast<const TrainingDefinitionRequest*>(
        &_TrainingDefinitionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TrainingDefinitionRequest& a, TrainingDefinitionRequest& b) { a.Swap(&b); }
  inline void Swap(TrainingDefinitionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainingDefinitionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainingDefinitionRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<TrainingDefinitionRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const TrainingDefinitionRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const TrainingDefinitionRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.TrainingDefinitionRequest"; }

 protected:
  explicit TrainingDefinitionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrainingDefinitionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrainingDefinitionRequest& from);
  TrainingDefinitionRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrainingDefinitionRequest&& from) noexcept
      : TrainingDefinitionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Schola.TrainingDefinitionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrainingDefinitionRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_GymConnector_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull TrainingDefinitionRequest_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API InitialStateRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Schola.InitialStateRequest) */ {
 public:
  inline InitialStateRequest() : InitialStateRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InitialStateRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InitialStateRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InitialStateRequest(::google::protobuf::internal::ConstantInitialized);

  inline InitialStateRequest(const InitialStateRequest& from) : InitialStateRequest(nullptr, from) {}
  inline InitialStateRequest(InitialStateRequest&& from) noexcept
      : InitialStateRequest(nullptr, ::std::move(from)) {}
  inline InitialStateRequest& operator=(const InitialStateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitialStateRequest& operator=(InitialStateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitialStateRequest& default_instance() {
    return *reinterpret_cast<const InitialStateRequest*>(
        &_InitialStateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(InitialStateRequest& a, InitialStateRequest& b) { a.Swap(&b); }
  inline void Swap(InitialStateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitialStateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitialStateRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<InitialStateRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const InitialStateRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const InitialStateRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.InitialStateRequest"; }

 protected:
  explicit InitialStateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InitialStateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InitialStateRequest& from);
  InitialStateRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InitialStateRequest&& from) noexcept
      : InitialStateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Schola.InitialStateRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InitialStateRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_GymConnector_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull InitialStateRequest_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API GymConnectorStartResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Schola.GymConnectorStartResponse) */ {
 public:
  inline GymConnectorStartResponse() : GymConnectorStartResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GymConnectorStartResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GymConnectorStartResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GymConnectorStartResponse(::google::protobuf::internal::ConstantInitialized);

  inline GymConnectorStartResponse(const GymConnectorStartResponse& from) : GymConnectorStartResponse(nullptr, from) {}
  inline GymConnectorStartResponse(GymConnectorStartResponse&& from) noexcept
      : GymConnectorStartResponse(nullptr, ::std::move(from)) {}
  inline GymConnectorStartResponse& operator=(const GymConnectorStartResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GymConnectorStartResponse& operator=(GymConnectorStartResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GymConnectorStartResponse& default_instance() {
    return *reinterpret_cast<const GymConnectorStartResponse*>(
        &_GymConnectorStartResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GymConnectorStartResponse& a, GymConnectorStartResponse& b) { a.Swap(&b); }
  inline void Swap(GymConnectorStartResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GymConnectorStartResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GymConnectorStartResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<GymConnectorStartResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GymConnectorStartResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GymConnectorStartResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.GymConnectorStartResponse"; }

 protected:
  explicit GymConnectorStartResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GymConnectorStartResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GymConnectorStartResponse& from);
  GymConnectorStartResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GymConnectorStartResponse&& from) noexcept
      : GymConnectorStartResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Schola.GymConnectorStartResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GymConnectorStartResponse& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_GymConnector_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull GymConnectorStartResponse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API GymConnectorStartRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.GymConnectorStartRequest) */ {
 public:
  inline GymConnectorStartRequest() : GymConnectorStartRequest(nullptr) {}
  ~GymConnectorStartRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GymConnectorStartRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GymConnectorStartRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GymConnectorStartRequest(::google::protobuf::internal::ConstantInitialized);

  inline GymConnectorStartRequest(const GymConnectorStartRequest& from) : GymConnectorStartRequest(nullptr, from) {}
  inline GymConnectorStartRequest(GymConnectorStartRequest&& from) noexcept
      : GymConnectorStartRequest(nullptr, ::std::move(from)) {}
  inline GymConnectorStartRequest& operator=(const GymConnectorStartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GymConnectorStartRequest& operator=(GymConnectorStartRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GymConnectorStartRequest& default_instance() {
    return *reinterpret_cast<const GymConnectorStartRequest*>(
        &_GymConnectorStartRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GymConnectorStartRequest& a, GymConnectorStartRequest& b) { a.Swap(&b); }
  inline void Swap(GymConnectorStartRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GymConnectorStartRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GymConnectorStartRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GymConnectorStartRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GymConnectorStartRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GymConnectorStartRequest& from) { GymConnectorStartRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GymConnectorStartRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.GymConnectorStartRequest"; }

 protected:
  explicit GymConnectorStartRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GymConnectorStartRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GymConnectorStartRequest& from);
  GymConnectorStartRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GymConnectorStartRequest&& from) noexcept
      : GymConnectorStartRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAutoresetTypeFieldNumber = 1,
  };
  // .Schola.AutoResetType autoreset_type = 1;
  void clear_autoreset_type() ;
  ::Schola::AutoResetType autoreset_type() const;
  void set_autoreset_type(::Schola::AutoResetType value);

  private:
  ::Schola::AutoResetType _internal_autoreset_type() const;
  void _internal_set_autoreset_type(::Schola::AutoResetType value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.GymConnectorStartRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GymConnectorStartRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int autoreset_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GymConnector_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull GymConnectorStartRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TrainingDefinitionRequest

// -------------------------------------------------------------------

// GymConnectorStartRequest

// .Schola.AutoResetType autoreset_type = 1;
inline void GymConnectorStartRequest::clear_autoreset_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.autoreset_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::Schola::AutoResetType GymConnectorStartRequest::autoreset_type() const {
  // @@protoc_insertion_point(field_get:Schola.GymConnectorStartRequest.autoreset_type)
  return _internal_autoreset_type();
}
inline void GymConnectorStartRequest::set_autoreset_type(::Schola::AutoResetType value) {
  _internal_set_autoreset_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.GymConnectorStartRequest.autoreset_type)
}
inline ::Schola::AutoResetType GymConnectorStartRequest::_internal_autoreset_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Schola::AutoResetType>(_impl_.autoreset_type_);
}
inline void GymConnectorStartRequest::_internal_set_autoreset_type(::Schola::AutoResetType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.autoreset_type_ = value;
}

// -------------------------------------------------------------------

// GymConnectorStartResponse

// -------------------------------------------------------------------

// InitialStateRequest

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Schola::AutoResetType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Schola::AutoResetType>() {
  return ::Schola::AutoResetType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // GymConnector_2eproto_2epb_2eh
