// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ImitationState.proto
// Protobuf C++ Version: 6.31.1

#ifndef ImitationState_2eproto_2epb_2eh
#define ImitationState_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "Points.pb.h"
#include "State.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ImitationState_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_ImitationState_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ImitationState_2eproto;
}  // extern "C"
namespace Schola {
class ImitationAgentState;
struct ImitationAgentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationAgentStateDefaultTypeInternal _ImitationAgentState_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationAgentState_class_data_;
class ImitationAgentState_InfoEntry_DoNotUse;
struct ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal _ImitationAgentState_InfoEntry_DoNotUse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationAgentState_InfoEntry_DoNotUse_class_data_;
class ImitationEnvironmentState;
struct ImitationEnvironmentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationEnvironmentStateDefaultTypeInternal _ImitationEnvironmentState_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationEnvironmentState_class_data_;
class ImitationEnvironmentState_AgentStatesEntry_DoNotUse;
struct ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _ImitationEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationEnvironmentState_AgentStatesEntry_DoNotUse_class_data_;
class ImitationState;
struct ImitationStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationStateDefaultTypeInternal _ImitationState_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationState_class_data_;
class ImitationTrainingState;
struct ImitationTrainingStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern ImitationTrainingStateDefaultTypeInternal _ImitationTrainingState_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationTrainingState_class_data_;
}  // namespace Schola
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Schola {

// ===================================================================


// -------------------------------------------------------------------

class ImitationAgentState_InfoEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<std::string, std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  ImitationAgentState_InfoEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationAgentState_InfoEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit ImitationAgentState_InfoEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_ImitationAgentState_InfoEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ImitationState_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 53,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationAgentState_InfoEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API ImitationAgentState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.ImitationAgentState) */ {
 public:
  inline ImitationAgentState() : ImitationAgentState(nullptr) {}
  ~ImitationAgentState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImitationAgentState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImitationAgentState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationAgentState(::google::protobuf::internal::ConstantInitialized);

  inline ImitationAgentState(const ImitationAgentState& from) : ImitationAgentState(nullptr, from) {}
  inline ImitationAgentState(ImitationAgentState&& from) noexcept
      : ImitationAgentState(nullptr, ::std::move(from)) {}
  inline ImitationAgentState& operator=(const ImitationAgentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImitationAgentState& operator=(ImitationAgentState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImitationAgentState& default_instance() {
    return *reinterpret_cast<const ImitationAgentState*>(
        &_ImitationAgentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ImitationAgentState& a, ImitationAgentState& b) { a.Swap(&b); }
  inline void Swap(ImitationAgentState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImitationAgentState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImitationAgentState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImitationAgentState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImitationAgentState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImitationAgentState& from) { ImitationAgentState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImitationAgentState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.ImitationAgentState"; }

 protected:
  explicit ImitationAgentState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImitationAgentState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImitationAgentState& from);
  ImitationAgentState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImitationAgentState&& from) noexcept
      : ImitationAgentState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInfoFieldNumber = 5,
    kObservationsFieldNumber = 1,
    kActionsFieldNumber = 6,
    kRewardFieldNumber = 2,
    kTerminatedFieldNumber = 3,
    kTruncatedFieldNumber = 4,
  };
  // map<string, string> info = 5;
  int info_size() const;
  private:
  int _internal_info_size() const;

  public:
  void clear_info() ;
  const ::google::protobuf::Map<std::string, std::string>& info() const;
  ::google::protobuf::Map<std::string, std::string>* PROTOBUF_NONNULL mutable_info();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_info() const;
  ::google::protobuf::Map<std::string, std::string>* PROTOBUF_NONNULL _internal_mutable_info();

  public:
  // .Schola.Point observations = 1;
  bool has_observations() const;
  void clear_observations() ;
  const ::Schola::Point& observations() const;
  [[nodiscard]] ::Schola::Point* PROTOBUF_NULLABLE release_observations();
  ::Schola::Point* PROTOBUF_NONNULL mutable_observations();
  void set_allocated_observations(::Schola::Point* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_observations(::Schola::Point* PROTOBUF_NULLABLE value);
  ::Schola::Point* PROTOBUF_NULLABLE unsafe_arena_release_observations();

  private:
  const ::Schola::Point& _internal_observations() const;
  ::Schola::Point* PROTOBUF_NONNULL _internal_mutable_observations();

  public:
  // .Schola.Point actions = 6;
  bool has_actions() const;
  void clear_actions() ;
  const ::Schola::Point& actions() const;
  [[nodiscard]] ::Schola::Point* PROTOBUF_NULLABLE release_actions();
  ::Schola::Point* PROTOBUF_NONNULL mutable_actions();
  void set_allocated_actions(::Schola::Point* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_actions(::Schola::Point* PROTOBUF_NULLABLE value);
  ::Schola::Point* PROTOBUF_NULLABLE unsafe_arena_release_actions();

  private:
  const ::Schola::Point& _internal_actions() const;
  ::Schola::Point* PROTOBUF_NONNULL _internal_mutable_actions();

  public:
  // float reward = 2;
  void clear_reward() ;
  float reward() const;
  void set_reward(float value);

  private:
  float _internal_reward() const;
  void _internal_set_reward(float value);

  public:
  // bool terminated = 3;
  void clear_terminated() ;
  bool terminated() const;
  void set_terminated(bool value);

  private:
  bool _internal_terminated() const;
  void _internal_set_terminated(bool value);

  public:
  // bool truncated = 4;
  void clear_truncated() ;
  bool truncated() const;
  void set_truncated(bool value);

  private:
  bool _internal_truncated() const;
  void _internal_set_truncated(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.ImitationAgentState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   3, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImitationAgentState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<ImitationAgentState_InfoEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        info_;
    ::Schola::Point* PROTOBUF_NULLABLE observations_;
    ::Schola::Point* PROTOBUF_NULLABLE actions_;
    float reward_;
    bool terminated_;
    bool truncated_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ImitationState_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationAgentState_class_data_;
// -------------------------------------------------------------------

class ImitationEnvironmentState_AgentStatesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  ImitationEnvironmentState_AgentStatesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationEnvironmentState_AgentStatesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit ImitationEnvironmentState_AgentStatesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_ImitationEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ImitationState_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 61,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationEnvironmentState_AgentStatesEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API ImitationEnvironmentState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.ImitationEnvironmentState) */ {
 public:
  inline ImitationEnvironmentState() : ImitationEnvironmentState(nullptr) {}
  ~ImitationEnvironmentState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImitationEnvironmentState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImitationEnvironmentState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationEnvironmentState(::google::protobuf::internal::ConstantInitialized);

  inline ImitationEnvironmentState(const ImitationEnvironmentState& from) : ImitationEnvironmentState(nullptr, from) {}
  inline ImitationEnvironmentState(ImitationEnvironmentState&& from) noexcept
      : ImitationEnvironmentState(nullptr, ::std::move(from)) {}
  inline ImitationEnvironmentState& operator=(const ImitationEnvironmentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImitationEnvironmentState& operator=(ImitationEnvironmentState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImitationEnvironmentState& default_instance() {
    return *reinterpret_cast<const ImitationEnvironmentState*>(
        &_ImitationEnvironmentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ImitationEnvironmentState& a, ImitationEnvironmentState& b) { a.Swap(&b); }
  inline void Swap(ImitationEnvironmentState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImitationEnvironmentState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImitationEnvironmentState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImitationEnvironmentState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImitationEnvironmentState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImitationEnvironmentState& from) { ImitationEnvironmentState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImitationEnvironmentState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.ImitationEnvironmentState"; }

 protected:
  explicit ImitationEnvironmentState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImitationEnvironmentState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImitationEnvironmentState& from);
  ImitationEnvironmentState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImitationEnvironmentState&& from) noexcept
      : ImitationEnvironmentState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAgentStatesFieldNumber = 1,
  };
  // map<string, .Schola.ImitationAgentState> agent_states = 1;
  int agent_states_size() const;
  private:
  int _internal_agent_states_size() const;

  public:
  void clear_agent_states() ;
  const ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>& agent_states() const;
  ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>* PROTOBUF_NONNULL mutable_agent_states();

  private:
  const ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>& _internal_agent_states() const;
  ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>* PROTOBUF_NONNULL _internal_mutable_agent_states();

  public:
  // @@protoc_insertion_point(class_scope:Schola.ImitationEnvironmentState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImitationEnvironmentState& from_msg);
    ::google::protobuf::internal::MapField<ImitationEnvironmentState_AgentStatesEntry_DoNotUse, std::string, ::Schola::ImitationAgentState,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        agent_states_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ImitationState_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationEnvironmentState_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API ImitationTrainingState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.ImitationTrainingState) */ {
 public:
  inline ImitationTrainingState() : ImitationTrainingState(nullptr) {}
  ~ImitationTrainingState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImitationTrainingState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImitationTrainingState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationTrainingState(::google::protobuf::internal::ConstantInitialized);

  inline ImitationTrainingState(const ImitationTrainingState& from) : ImitationTrainingState(nullptr, from) {}
  inline ImitationTrainingState(ImitationTrainingState&& from) noexcept
      : ImitationTrainingState(nullptr, ::std::move(from)) {}
  inline ImitationTrainingState& operator=(const ImitationTrainingState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImitationTrainingState& operator=(ImitationTrainingState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImitationTrainingState& default_instance() {
    return *reinterpret_cast<const ImitationTrainingState*>(
        &_ImitationTrainingState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ImitationTrainingState& a, ImitationTrainingState& b) { a.Swap(&b); }
  inline void Swap(ImitationTrainingState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImitationTrainingState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImitationTrainingState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImitationTrainingState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImitationTrainingState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImitationTrainingState& from) { ImitationTrainingState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImitationTrainingState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.ImitationTrainingState"; }

 protected:
  explicit ImitationTrainingState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImitationTrainingState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImitationTrainingState& from);
  ImitationTrainingState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImitationTrainingState&& from) noexcept
      : ImitationTrainingState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnvironmentStatesFieldNumber = 1,
  };
  // repeated .Schola.ImitationEnvironmentState environment_states = 1;
  int environment_states_size() const;
  private:
  int _internal_environment_states_size() const;

  public:
  void clear_environment_states() ;
  ::Schola::ImitationEnvironmentState* PROTOBUF_NONNULL mutable_environment_states(int index);
  ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>* PROTOBUF_NONNULL mutable_environment_states();

  private:
  const ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>& _internal_environment_states() const;
  ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>* PROTOBUF_NONNULL _internal_mutable_environment_states();
  public:
  const ::Schola::ImitationEnvironmentState& environment_states(int index) const;
  ::Schola::ImitationEnvironmentState* PROTOBUF_NONNULL add_environment_states();
  const ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>& environment_states() const;
  // @@protoc_insertion_point(class_scope:Schola.ImitationTrainingState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImitationTrainingState& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Schola::ImitationEnvironmentState > environment_states_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ImitationState_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationTrainingState_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API ImitationState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.ImitationState) */ {
 public:
  inline ImitationState() : ImitationState(nullptr) {}
  ~ImitationState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImitationState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImitationState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImitationState(::google::protobuf::internal::ConstantInitialized);

  inline ImitationState(const ImitationState& from) : ImitationState(nullptr, from) {}
  inline ImitationState(ImitationState&& from) noexcept
      : ImitationState(nullptr, ::std::move(from)) {}
  inline ImitationState& operator=(const ImitationState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImitationState& operator=(ImitationState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImitationState& default_instance() {
    return *reinterpret_cast<const ImitationState*>(
        &_ImitationState_default_instance_);
  }
  enum OptionalTrainingStateCase {
    kTrainingState = 1,
    OPTIONAL_TRAINING_STATE_NOT_SET = 0,
  };
  enum OptionalInitialStateCase {
    kInitialState = 2,
    OPTIONAL_INITIAL_STATE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(ImitationState& a, ImitationState& b) { a.Swap(&b); }
  inline void Swap(ImitationState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImitationState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImitationState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImitationState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImitationState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImitationState& from) { ImitationState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImitationState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.ImitationState"; }

 protected:
  explicit ImitationState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImitationState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImitationState& from);
  ImitationState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImitationState&& from) noexcept
      : ImitationState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTrainingStateFieldNumber = 1,
    kInitialStateFieldNumber = 2,
  };
  // .Schola.ImitationTrainingState training_state = 1;
  bool has_training_state() const;
  private:
  bool _internal_has_training_state() const;

  public:
  void clear_training_state() ;
  const ::Schola::ImitationTrainingState& training_state() const;
  [[nodiscard]] ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE release_training_state();
  ::Schola::ImitationTrainingState* PROTOBUF_NONNULL mutable_training_state();
  void set_allocated_training_state(::Schola::ImitationTrainingState* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_training_state(::Schola::ImitationTrainingState* PROTOBUF_NULLABLE value);
  ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE unsafe_arena_release_training_state();

  private:
  const ::Schola::ImitationTrainingState& _internal_training_state() const;
  ::Schola::ImitationTrainingState* PROTOBUF_NONNULL _internal_mutable_training_state();

  public:
  // .Schola.InitialState initial_state = 2;
  bool has_initial_state() const;
  private:
  bool _internal_has_initial_state() const;

  public:
  void clear_initial_state() ;
  const ::Schola::InitialState& initial_state() const;
  [[nodiscard]] ::Schola::InitialState* PROTOBUF_NULLABLE release_initial_state();
  ::Schola::InitialState* PROTOBUF_NONNULL mutable_initial_state();
  void set_allocated_initial_state(::Schola::InitialState* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_initial_state(::Schola::InitialState* PROTOBUF_NULLABLE value);
  ::Schola::InitialState* PROTOBUF_NULLABLE unsafe_arena_release_initial_state();

  private:
  const ::Schola::InitialState& _internal_initial_state() const;
  ::Schola::InitialState* PROTOBUF_NONNULL _internal_mutable_initial_state();

  public:
  void clear_optional_training_state();
  OptionalTrainingStateCase optional_training_state_case() const;
  void clear_optional_initial_state();
  OptionalInitialStateCase optional_initial_state_case() const;
  // @@protoc_insertion_point(class_scope:Schola.ImitationState)
 private:
  class _Internal;
  void set_has_training_state();
  void set_has_initial_state();
  inline bool has_optional_training_state() const;
  inline void clear_has_optional_training_state();
  inline bool has_optional_initial_state() const;
  inline void clear_has_optional_initial_state();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImitationState& from_msg);
    union OptionalTrainingStateUnion {
      constexpr OptionalTrainingStateUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE training_state_;
    } optional_training_state_;
    union OptionalInitialStateUnion {
      constexpr OptionalInitialStateUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Schola::InitialState* PROTOBUF_NULLABLE initial_state_;
    } optional_initial_state_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[2];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ImitationState_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull ImitationState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ImitationAgentState

// .Schola.Point observations = 1;
inline bool ImitationAgentState::has_observations() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.observations_ != nullptr);
  return value;
}
inline const ::Schola::Point& ImitationAgentState::_internal_observations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Schola::Point* p = _impl_.observations_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Point&>(::Schola::_Point_default_instance_);
}
inline const ::Schola::Point& ImitationAgentState::observations() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.ImitationAgentState.observations)
  return _internal_observations();
}
inline void ImitationAgentState::unsafe_arena_set_allocated_observations(
    ::Schola::Point* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.observations_);
  }
  _impl_.observations_ = reinterpret_cast<::Schola::Point*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.ImitationAgentState.observations)
}
inline ::Schola::Point* PROTOBUF_NULLABLE ImitationAgentState::release_observations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Schola::Point* released = _impl_.observations_;
  _impl_.observations_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Schola::Point* PROTOBUF_NULLABLE ImitationAgentState::unsafe_arena_release_observations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Schola.ImitationAgentState.observations)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Schola::Point* temp = _impl_.observations_;
  _impl_.observations_ = nullptr;
  return temp;
}
inline ::Schola::Point* PROTOBUF_NONNULL ImitationAgentState::_internal_mutable_observations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.observations_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Schola::Point>(GetArena());
    _impl_.observations_ = reinterpret_cast<::Schola::Point*>(p);
  }
  return _impl_.observations_;
}
inline ::Schola::Point* PROTOBUF_NONNULL ImitationAgentState::mutable_observations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Schola::Point* _msg = _internal_mutable_observations();
  // @@protoc_insertion_point(field_mutable:Schola.ImitationAgentState.observations)
  return _msg;
}
inline void ImitationAgentState::set_allocated_observations(::Schola::Point* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.observations_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.observations_ = reinterpret_cast<::Schola::Point*>(value);
  // @@protoc_insertion_point(field_set_allocated:Schola.ImitationAgentState.observations)
}

// float reward = 2;
inline void ImitationAgentState::clear_reward() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reward_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float ImitationAgentState::reward() const {
  // @@protoc_insertion_point(field_get:Schola.ImitationAgentState.reward)
  return _internal_reward();
}
inline void ImitationAgentState::set_reward(float value) {
  _internal_set_reward(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:Schola.ImitationAgentState.reward)
}
inline float ImitationAgentState::_internal_reward() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reward_;
}
inline void ImitationAgentState::_internal_set_reward(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reward_ = value;
}

// bool terminated = 3;
inline void ImitationAgentState::clear_terminated() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.terminated_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool ImitationAgentState::terminated() const {
  // @@protoc_insertion_point(field_get:Schola.ImitationAgentState.terminated)
  return _internal_terminated();
}
inline void ImitationAgentState::set_terminated(bool value) {
  _internal_set_terminated(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:Schola.ImitationAgentState.terminated)
}
inline bool ImitationAgentState::_internal_terminated() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.terminated_;
}
inline void ImitationAgentState::_internal_set_terminated(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.terminated_ = value;
}

// bool truncated = 4;
inline void ImitationAgentState::clear_truncated() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.truncated_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool ImitationAgentState::truncated() const {
  // @@protoc_insertion_point(field_get:Schola.ImitationAgentState.truncated)
  return _internal_truncated();
}
inline void ImitationAgentState::set_truncated(bool value) {
  _internal_set_truncated(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:Schola.ImitationAgentState.truncated)
}
inline bool ImitationAgentState::_internal_truncated() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.truncated_;
}
inline void ImitationAgentState::_internal_set_truncated(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.truncated_ = value;
}

// map<string, string> info = 5;
inline int ImitationAgentState::_internal_info_size() const {
  return _internal_info().size();
}
inline int ImitationAgentState::info_size() const {
  return _internal_info_size();
}
inline void ImitationAgentState::clear_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& ImitationAgentState::_internal_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.info_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& ImitationAgentState::info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Schola.ImitationAgentState.info)
  return _internal_info();
}
inline ::google::protobuf::Map<std::string, std::string>* PROTOBUF_NONNULL ImitationAgentState::_internal_mutable_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.info_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* PROTOBUF_NONNULL ImitationAgentState::mutable_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Schola.ImitationAgentState.info)
  return _internal_mutable_info();
}

// .Schola.Point actions = 6;
inline bool ImitationAgentState::has_actions() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.actions_ != nullptr);
  return value;
}
inline const ::Schola::Point& ImitationAgentState::_internal_actions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Schola::Point* p = _impl_.actions_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Point&>(::Schola::_Point_default_instance_);
}
inline const ::Schola::Point& ImitationAgentState::actions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.ImitationAgentState.actions)
  return _internal_actions();
}
inline void ImitationAgentState::unsafe_arena_set_allocated_actions(
    ::Schola::Point* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.actions_);
  }
  _impl_.actions_ = reinterpret_cast<::Schola::Point*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.ImitationAgentState.actions)
}
inline ::Schola::Point* PROTOBUF_NULLABLE ImitationAgentState::release_actions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Schola::Point* released = _impl_.actions_;
  _impl_.actions_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Schola::Point* PROTOBUF_NULLABLE ImitationAgentState::unsafe_arena_release_actions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Schola.ImitationAgentState.actions)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Schola::Point* temp = _impl_.actions_;
  _impl_.actions_ = nullptr;
  return temp;
}
inline ::Schola::Point* PROTOBUF_NONNULL ImitationAgentState::_internal_mutable_actions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.actions_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Schola::Point>(GetArena());
    _impl_.actions_ = reinterpret_cast<::Schola::Point*>(p);
  }
  return _impl_.actions_;
}
inline ::Schola::Point* PROTOBUF_NONNULL ImitationAgentState::mutable_actions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Schola::Point* _msg = _internal_mutable_actions();
  // @@protoc_insertion_point(field_mutable:Schola.ImitationAgentState.actions)
  return _msg;
}
inline void ImitationAgentState::set_allocated_actions(::Schola::Point* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.actions_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.actions_ = reinterpret_cast<::Schola::Point*>(value);
  // @@protoc_insertion_point(field_set_allocated:Schola.ImitationAgentState.actions)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ImitationEnvironmentState

// map<string, .Schola.ImitationAgentState> agent_states = 1;
inline int ImitationEnvironmentState::_internal_agent_states_size() const {
  return _internal_agent_states().size();
}
inline int ImitationEnvironmentState::agent_states_size() const {
  return _internal_agent_states_size();
}
inline void ImitationEnvironmentState::clear_agent_states() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agent_states_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>& ImitationEnvironmentState::_internal_agent_states() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.agent_states_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>& ImitationEnvironmentState::agent_states() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Schola.ImitationEnvironmentState.agent_states)
  return _internal_agent_states();
}
inline ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>* PROTOBUF_NONNULL ImitationEnvironmentState::_internal_mutable_agent_states() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.agent_states_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::Schola::ImitationAgentState>* PROTOBUF_NONNULL ImitationEnvironmentState::mutable_agent_states()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Schola.ImitationEnvironmentState.agent_states)
  return _internal_mutable_agent_states();
}

// -------------------------------------------------------------------

// ImitationTrainingState

// repeated .Schola.ImitationEnvironmentState environment_states = 1;
inline int ImitationTrainingState::_internal_environment_states_size() const {
  return _internal_environment_states().size();
}
inline int ImitationTrainingState::environment_states_size() const {
  return _internal_environment_states_size();
}
inline void ImitationTrainingState::clear_environment_states() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_states_.Clear();
}
inline ::Schola::ImitationEnvironmentState* PROTOBUF_NONNULL ImitationTrainingState::mutable_environment_states(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Schola.ImitationTrainingState.environment_states)
  return _internal_mutable_environment_states()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>* PROTOBUF_NONNULL ImitationTrainingState::mutable_environment_states()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.ImitationTrainingState.environment_states)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_environment_states();
}
inline const ::Schola::ImitationEnvironmentState& ImitationTrainingState::environment_states(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.ImitationTrainingState.environment_states)
  return _internal_environment_states().Get(index);
}
inline ::Schola::ImitationEnvironmentState* PROTOBUF_NONNULL ImitationTrainingState::add_environment_states()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Schola::ImitationEnvironmentState* _add = _internal_mutable_environment_states()->Add();
  // @@protoc_insertion_point(field_add:Schola.ImitationTrainingState.environment_states)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>& ImitationTrainingState::environment_states() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.ImitationTrainingState.environment_states)
  return _internal_environment_states();
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>&
ImitationTrainingState::_internal_environment_states() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.environment_states_;
}
inline ::google::protobuf::RepeatedPtrField<::Schola::ImitationEnvironmentState>* PROTOBUF_NONNULL
ImitationTrainingState::_internal_mutable_environment_states() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.environment_states_;
}

// -------------------------------------------------------------------

// ImitationState

// .Schola.ImitationTrainingState training_state = 1;
inline bool ImitationState::has_training_state() const {
  return optional_training_state_case() == kTrainingState;
}
inline bool ImitationState::_internal_has_training_state() const {
  return optional_training_state_case() == kTrainingState;
}
inline void ImitationState::set_has_training_state() {
  _impl_._oneof_case_[0] = kTrainingState;
}
inline void ImitationState::clear_training_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (optional_training_state_case() == kTrainingState) {
    if (GetArena() == nullptr) {
      delete _impl_.optional_training_state_.training_state_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.optional_training_state_.training_state_);
    }
    clear_has_optional_training_state();
  }
}
inline ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE ImitationState::release_training_state() {
  // @@protoc_insertion_point(field_release:Schola.ImitationState.training_state)
  if (optional_training_state_case() == kTrainingState) {
    clear_has_optional_training_state();
    auto* temp = _impl_.optional_training_state_.training_state_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.optional_training_state_.training_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::ImitationTrainingState& ImitationState::_internal_training_state() const {
  return optional_training_state_case() == kTrainingState ? *_impl_.optional_training_state_.training_state_ : reinterpret_cast<::Schola::ImitationTrainingState&>(::Schola::_ImitationTrainingState_default_instance_);
}
inline const ::Schola::ImitationTrainingState& ImitationState::training_state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.ImitationState.training_state)
  return _internal_training_state();
}
inline ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE ImitationState::unsafe_arena_release_training_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.ImitationState.training_state)
  if (optional_training_state_case() == kTrainingState) {
    clear_has_optional_training_state();
    auto* temp = _impl_.optional_training_state_.training_state_;
    _impl_.optional_training_state_.training_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ImitationState::unsafe_arena_set_allocated_training_state(
    ::Schola::ImitationTrainingState* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_optional_training_state();
  if (value) {
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.ImitationState.training_state)
}
inline ::Schola::ImitationTrainingState* PROTOBUF_NONNULL ImitationState::_internal_mutable_training_state() {
  if (optional_training_state_case() != kTrainingState) {
    clear_optional_training_state();
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = 
        ::google::protobuf::Message::DefaultConstruct<::Schola::ImitationTrainingState>(GetArena());
  }
  return _impl_.optional_training_state_.training_state_;
}
inline ::Schola::ImitationTrainingState* PROTOBUF_NONNULL ImitationState::mutable_training_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::ImitationTrainingState* _msg = _internal_mutable_training_state();
  // @@protoc_insertion_point(field_mutable:Schola.ImitationState.training_state)
  return _msg;
}

// .Schola.InitialState initial_state = 2;
inline bool ImitationState::has_initial_state() const {
  return optional_initial_state_case() == kInitialState;
}
inline bool ImitationState::_internal_has_initial_state() const {
  return optional_initial_state_case() == kInitialState;
}
inline void ImitationState::set_has_initial_state() {
  _impl_._oneof_case_[1] = kInitialState;
}
inline ::Schola::InitialState* PROTOBUF_NULLABLE ImitationState::release_initial_state() {
  // @@protoc_insertion_point(field_release:Schola.ImitationState.initial_state)
  if (optional_initial_state_case() == kInitialState) {
    clear_has_optional_initial_state();
    auto* temp = _impl_.optional_initial_state_.initial_state_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.optional_initial_state_.initial_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::InitialState& ImitationState::_internal_initial_state() const {
  return optional_initial_state_case() == kInitialState ? *_impl_.optional_initial_state_.initial_state_ : reinterpret_cast<::Schola::InitialState&>(::Schola::_InitialState_default_instance_);
}
inline const ::Schola::InitialState& ImitationState::initial_state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.ImitationState.initial_state)
  return _internal_initial_state();
}
inline ::Schola::InitialState* PROTOBUF_NULLABLE ImitationState::unsafe_arena_release_initial_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.ImitationState.initial_state)
  if (optional_initial_state_case() == kInitialState) {
    clear_has_optional_initial_state();
    auto* temp = _impl_.optional_initial_state_.initial_state_;
    _impl_.optional_initial_state_.initial_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ImitationState::unsafe_arena_set_allocated_initial_state(
    ::Schola::InitialState* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_optional_initial_state();
  if (value) {
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.ImitationState.initial_state)
}
inline ::Schola::InitialState* PROTOBUF_NONNULL ImitationState::_internal_mutable_initial_state() {
  if (optional_initial_state_case() != kInitialState) {
    clear_optional_initial_state();
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = 
        ::google::protobuf::Message::DefaultConstruct<::Schola::InitialState>(GetArena());
  }
  return _impl_.optional_initial_state_.initial_state_;
}
inline ::Schola::InitialState* PROTOBUF_NONNULL ImitationState::mutable_initial_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::InitialState* _msg = _internal_mutable_initial_state();
  // @@protoc_insertion_point(field_mutable:Schola.ImitationState.initial_state)
  return _msg;
}

inline bool ImitationState::has_optional_training_state() const {
  return optional_training_state_case() != OPTIONAL_TRAINING_STATE_NOT_SET;
}
inline void ImitationState::clear_has_optional_training_state() {
  _impl_._oneof_case_[0] = OPTIONAL_TRAINING_STATE_NOT_SET;
}
inline bool ImitationState::has_optional_initial_state() const {
  return optional_initial_state_case() != OPTIONAL_INITIAL_STATE_NOT_SET;
}
inline void ImitationState::clear_has_optional_initial_state() {
  _impl_._oneof_case_[1] = OPTIONAL_INITIAL_STATE_NOT_SET;
}
inline ImitationState::OptionalTrainingStateCase ImitationState::optional_training_state_case() const {
  return ImitationState::OptionalTrainingStateCase(_impl_._oneof_case_[0]);
}
inline ImitationState::OptionalInitialStateCase ImitationState::optional_initial_state_case() const {
  return ImitationState::OptionalInitialStateCase(_impl_._oneof_case_[1]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // ImitationState_2eproto_2epb_2eh
