// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Points.proto
// Protobuf C++ Version: 6.31.1

#ifndef Points_2eproto_2epb_2eh
#define Points_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "DType.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Points_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_Points_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Points_2eproto;
}  // extern "C"
namespace Schola {
class BoxPoint;
struct BoxPointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern BoxPointDefaultTypeInternal _BoxPoint_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxPoint_class_data_;
class DictPoint;
struct DictPointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DictPointDefaultTypeInternal _DictPoint_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictPoint_class_data_;
class DictPoint_ValuesEntry_DoNotUse;
struct DictPoint_ValuesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DictPoint_ValuesEntry_DoNotUseDefaultTypeInternal _DictPoint_ValuesEntry_DoNotUse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictPoint_ValuesEntry_DoNotUse_class_data_;
class DiscretePoint;
struct DiscretePointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DiscretePointDefaultTypeInternal _DiscretePoint_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DiscretePoint_class_data_;
class MultiBinaryPoint;
struct MultiBinaryPointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern MultiBinaryPointDefaultTypeInternal _MultiBinaryPoint_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiBinaryPoint_class_data_;
class MultiDiscretePoint;
struct MultiDiscretePointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern MultiDiscretePointDefaultTypeInternal _MultiDiscretePoint_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiDiscretePoint_class_data_;
class Point;
struct PointDefaultTypeInternal;
SCHOLAPROTOBUF_API extern PointDefaultTypeInternal _Point_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull Point_class_data_;
}  // namespace Schola
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Schola {

// ===================================================================


// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API MultiDiscretePoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.MultiDiscretePoint) */ {
 public:
  inline MultiDiscretePoint() : MultiDiscretePoint(nullptr) {}
  ~MultiDiscretePoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MultiDiscretePoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MultiDiscretePoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MultiDiscretePoint(::google::protobuf::internal::ConstantInitialized);

  inline MultiDiscretePoint(const MultiDiscretePoint& from) : MultiDiscretePoint(nullptr, from) {}
  inline MultiDiscretePoint(MultiDiscretePoint&& from) noexcept
      : MultiDiscretePoint(nullptr, ::std::move(from)) {}
  inline MultiDiscretePoint& operator=(const MultiDiscretePoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiDiscretePoint& operator=(MultiDiscretePoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiDiscretePoint& default_instance() {
    return *reinterpret_cast<const MultiDiscretePoint*>(
        &_MultiDiscretePoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MultiDiscretePoint& a, MultiDiscretePoint& b) { a.Swap(&b); }
  inline void Swap(MultiDiscretePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiDiscretePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiDiscretePoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MultiDiscretePoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MultiDiscretePoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MultiDiscretePoint& from) { MultiDiscretePoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MultiDiscretePoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.MultiDiscretePoint"; }

 protected:
  explicit MultiDiscretePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MultiDiscretePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MultiDiscretePoint& from);
  MultiDiscretePoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MultiDiscretePoint&& from) noexcept
      : MultiDiscretePoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 1,
  };
  // repeated int32 values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  ::int32_t values(int index) const;
  void set_values(int index, ::int32_t value);
  void add_values(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& values() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_values() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_values();

  public:
  // @@protoc_insertion_point(class_scope:Schola.MultiDiscretePoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MultiDiscretePoint& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> values_;
    ::google::protobuf::internal::CachedSize _values_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiDiscretePoint_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API MultiBinaryPoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.MultiBinaryPoint) */ {
 public:
  inline MultiBinaryPoint() : MultiBinaryPoint(nullptr) {}
  ~MultiBinaryPoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MultiBinaryPoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MultiBinaryPoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MultiBinaryPoint(::google::protobuf::internal::ConstantInitialized);

  inline MultiBinaryPoint(const MultiBinaryPoint& from) : MultiBinaryPoint(nullptr, from) {}
  inline MultiBinaryPoint(MultiBinaryPoint&& from) noexcept
      : MultiBinaryPoint(nullptr, ::std::move(from)) {}
  inline MultiBinaryPoint& operator=(const MultiBinaryPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiBinaryPoint& operator=(MultiBinaryPoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiBinaryPoint& default_instance() {
    return *reinterpret_cast<const MultiBinaryPoint*>(
        &_MultiBinaryPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MultiBinaryPoint& a, MultiBinaryPoint& b) { a.Swap(&b); }
  inline void Swap(MultiBinaryPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiBinaryPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiBinaryPoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MultiBinaryPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MultiBinaryPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MultiBinaryPoint& from) { MultiBinaryPoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MultiBinaryPoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.MultiBinaryPoint"; }

 protected:
  explicit MultiBinaryPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MultiBinaryPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MultiBinaryPoint& from);
  MultiBinaryPoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MultiBinaryPoint&& from) noexcept
      : MultiBinaryPoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 1,
  };
  // repeated bool values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  bool values(int index) const;
  void set_values(int index, bool value);
  void add_values(bool value);
  const ::google::protobuf::RepeatedField<bool>& values() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::RepeatedField<bool>& _internal_values() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL _internal_mutable_values();

  public:
  // @@protoc_insertion_point(class_scope:Schola.MultiBinaryPoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MultiBinaryPoint& from_msg);
    ::google::protobuf::RepeatedField<bool> values_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiBinaryPoint_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API DiscretePoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.DiscretePoint) */ {
 public:
  inline DiscretePoint() : DiscretePoint(nullptr) {}
  ~DiscretePoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiscretePoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiscretePoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiscretePoint(::google::protobuf::internal::ConstantInitialized);

  inline DiscretePoint(const DiscretePoint& from) : DiscretePoint(nullptr, from) {}
  inline DiscretePoint(DiscretePoint&& from) noexcept
      : DiscretePoint(nullptr, ::std::move(from)) {}
  inline DiscretePoint& operator=(const DiscretePoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiscretePoint& operator=(DiscretePoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiscretePoint& default_instance() {
    return *reinterpret_cast<const DiscretePoint*>(
        &_DiscretePoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DiscretePoint& a, DiscretePoint& b) { a.Swap(&b); }
  inline void Swap(DiscretePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiscretePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiscretePoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiscretePoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiscretePoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiscretePoint& from) { DiscretePoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiscretePoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.DiscretePoint"; }

 protected:
  explicit DiscretePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DiscretePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiscretePoint& from);
  DiscretePoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DiscretePoint&& from) noexcept
      : DiscretePoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
  };
  // int32 value = 1;
  void clear_value() ;
  ::int32_t value() const;
  void set_value(::int32_t value);

  private:
  ::int32_t _internal_value() const;
  void _internal_set_value(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.DiscretePoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DiscretePoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DiscretePoint_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API BoxPoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.BoxPoint) */ {
 public:
  inline BoxPoint() : BoxPoint(nullptr) {}
  ~BoxPoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoxPoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoxPoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoxPoint(::google::protobuf::internal::ConstantInitialized);

  inline BoxPoint(const BoxPoint& from) : BoxPoint(nullptr, from) {}
  inline BoxPoint(BoxPoint&& from) noexcept
      : BoxPoint(nullptr, ::std::move(from)) {}
  inline BoxPoint& operator=(const BoxPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoxPoint& operator=(BoxPoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BoxPoint& default_instance() {
    return *reinterpret_cast<const BoxPoint*>(
        &_BoxPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BoxPoint& a, BoxPoint& b) { a.Swap(&b); }
  inline void Swap(BoxPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoxPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoxPoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BoxPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BoxPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BoxPoint& from) { BoxPoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoxPoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.BoxPoint"; }

 protected:
  explicit BoxPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BoxPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoxPoint& from);
  BoxPoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BoxPoint&& from) noexcept
      : BoxPoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 1,
    kShapeFieldNumber = 3,
    kDtypeFieldNumber = 2,
  };
  // repeated float values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  float values(int index) const;
  void set_values(int index, float value);
  void add_values(float value);
  const ::google::protobuf::RepeatedField<float>& values() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_values() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_values();

  public:
  // repeated int32 shape = 3;
  int shape_size() const;
  private:
  int _internal_shape_size() const;

  public:
  void clear_shape() ;
  ::int32_t shape(int index) const;
  void set_shape(int index, ::int32_t value);
  void add_shape(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_shape();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_shape();

  public:
  // .Schola.DType dtype = 2;
  void clear_dtype() ;
  ::Schola::DType dtype() const;
  void set_dtype(::Schola::DType value);

  private:
  ::Schola::DType _internal_dtype() const;
  void _internal_set_dtype(::Schola::DType value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.BoxPoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BoxPoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> values_;
    ::google::protobuf::RepeatedField<::int32_t> shape_;
    ::google::protobuf::internal::CachedSize _shape_cached_byte_size_;
    int dtype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxPoint_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API DictPoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.DictPoint) */ {
 public:
  inline DictPoint() : DictPoint(nullptr) {}
  ~DictPoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DictPoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DictPoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DictPoint(::google::protobuf::internal::ConstantInitialized);

  inline DictPoint(const DictPoint& from) : DictPoint(nullptr, from) {}
  inline DictPoint(DictPoint&& from) noexcept
      : DictPoint(nullptr, ::std::move(from)) {}
  inline DictPoint& operator=(const DictPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline DictPoint& operator=(DictPoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DictPoint& default_instance() {
    return *reinterpret_cast<const DictPoint*>(
        &_DictPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(DictPoint& a, DictPoint& b) { a.Swap(&b); }
  inline void Swap(DictPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DictPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DictPoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DictPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DictPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DictPoint& from) { DictPoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DictPoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.DictPoint"; }

 protected:
  explicit DictPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DictPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DictPoint& from);
  DictPoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DictPoint&& from) noexcept
      : DictPoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 1,
  };
  // map<string, .Schola.Point> values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  const ::google::protobuf::Map<std::string, ::Schola::Point>& values() const;
  ::google::protobuf::Map<std::string, ::Schola::Point>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::Map<std::string, ::Schola::Point>& _internal_values() const;
  ::google::protobuf::Map<std::string, ::Schola::Point>* PROTOBUF_NONNULL _internal_mutable_values();

  public:
  // @@protoc_insertion_point(class_scope:Schola.DictPoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DictPoint& from_msg);
    ::google::protobuf::internal::MapField<DictPoint_ValuesEntry_DoNotUse, std::string, ::Schola::Point,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        values_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictPoint_class_data_;
// -------------------------------------------------------------------

class DictPoint_ValuesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  DictPoint_ValuesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DictPoint_ValuesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit DictPoint_ValuesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_DictPoint_ValuesEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_Points_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 40,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictPoint_ValuesEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API Point final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Point* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Point));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Point(::google::protobuf::internal::ConstantInitialized);

  inline Point(const Point& from) : Point(nullptr, from) {}
  inline Point(Point&& from) noexcept
      : Point(nullptr, ::std::move(from)) {}
  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *reinterpret_cast<const Point*>(
        &_Point_default_instance_);
  }
  enum PointCase {
    kBoxPoint = 1,
    kDiscretePoint = 2,
    kMultiDiscretePoint = 3,
    kMultiBinaryPoint = 4,
    kDictPoint = 5,
    POINT_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(Point& a, Point& b) { a.Swap(&b); }
  inline void Swap(Point* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Point>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Point& from) { Point::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Point* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.Point"; }

 protected:
  explicit Point(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Point(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Point& from);
  Point(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Point&& from) noexcept
      : Point(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBoxPointFieldNumber = 1,
    kDiscretePointFieldNumber = 2,
    kMultiDiscretePointFieldNumber = 3,
    kMultiBinaryPointFieldNumber = 4,
    kDictPointFieldNumber = 5,
  };
  // .Schola.BoxPoint box_point = 1;
  bool has_box_point() const;
  private:
  bool _internal_has_box_point() const;

  public:
  void clear_box_point() ;
  const ::Schola::BoxPoint& box_point() const;
  [[nodiscard]] ::Schola::BoxPoint* PROTOBUF_NULLABLE release_box_point();
  ::Schola::BoxPoint* PROTOBUF_NONNULL mutable_box_point();
  void set_allocated_box_point(::Schola::BoxPoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_box_point(::Schola::BoxPoint* PROTOBUF_NULLABLE value);
  ::Schola::BoxPoint* PROTOBUF_NULLABLE unsafe_arena_release_box_point();

  private:
  const ::Schola::BoxPoint& _internal_box_point() const;
  ::Schola::BoxPoint* PROTOBUF_NONNULL _internal_mutable_box_point();

  public:
  // .Schola.DiscretePoint discrete_point = 2;
  bool has_discrete_point() const;
  private:
  bool _internal_has_discrete_point() const;

  public:
  void clear_discrete_point() ;
  const ::Schola::DiscretePoint& discrete_point() const;
  [[nodiscard]] ::Schola::DiscretePoint* PROTOBUF_NULLABLE release_discrete_point();
  ::Schola::DiscretePoint* PROTOBUF_NONNULL mutable_discrete_point();
  void set_allocated_discrete_point(::Schola::DiscretePoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_discrete_point(::Schola::DiscretePoint* PROTOBUF_NULLABLE value);
  ::Schola::DiscretePoint* PROTOBUF_NULLABLE unsafe_arena_release_discrete_point();

  private:
  const ::Schola::DiscretePoint& _internal_discrete_point() const;
  ::Schola::DiscretePoint* PROTOBUF_NONNULL _internal_mutable_discrete_point();

  public:
  // .Schola.MultiDiscretePoint multi_discrete_point = 3;
  bool has_multi_discrete_point() const;
  private:
  bool _internal_has_multi_discrete_point() const;

  public:
  void clear_multi_discrete_point() ;
  const ::Schola::MultiDiscretePoint& multi_discrete_point() const;
  [[nodiscard]] ::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE release_multi_discrete_point();
  ::Schola::MultiDiscretePoint* PROTOBUF_NONNULL mutable_multi_discrete_point();
  void set_allocated_multi_discrete_point(::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_multi_discrete_point(::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE value);
  ::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE unsafe_arena_release_multi_discrete_point();

  private:
  const ::Schola::MultiDiscretePoint& _internal_multi_discrete_point() const;
  ::Schola::MultiDiscretePoint* PROTOBUF_NONNULL _internal_mutable_multi_discrete_point();

  public:
  // .Schola.MultiBinaryPoint multi_binary_point = 4;
  bool has_multi_binary_point() const;
  private:
  bool _internal_has_multi_binary_point() const;

  public:
  void clear_multi_binary_point() ;
  const ::Schola::MultiBinaryPoint& multi_binary_point() const;
  [[nodiscard]] ::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE release_multi_binary_point();
  ::Schola::MultiBinaryPoint* PROTOBUF_NONNULL mutable_multi_binary_point();
  void set_allocated_multi_binary_point(::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_multi_binary_point(::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE value);
  ::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE unsafe_arena_release_multi_binary_point();

  private:
  const ::Schola::MultiBinaryPoint& _internal_multi_binary_point() const;
  ::Schola::MultiBinaryPoint* PROTOBUF_NONNULL _internal_mutable_multi_binary_point();

  public:
  // .Schola.DictPoint dict_point = 5;
  bool has_dict_point() const;
  private:
  bool _internal_has_dict_point() const;

  public:
  void clear_dict_point() ;
  const ::Schola::DictPoint& dict_point() const;
  [[nodiscard]] ::Schola::DictPoint* PROTOBUF_NULLABLE release_dict_point();
  ::Schola::DictPoint* PROTOBUF_NONNULL mutable_dict_point();
  void set_allocated_dict_point(::Schola::DictPoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_dict_point(::Schola::DictPoint* PROTOBUF_NULLABLE value);
  ::Schola::DictPoint* PROTOBUF_NULLABLE unsafe_arena_release_dict_point();

  private:
  const ::Schola::DictPoint& _internal_dict_point() const;
  ::Schola::DictPoint* PROTOBUF_NONNULL _internal_mutable_dict_point();

  public:
  void clear_point();
  PointCase point_case() const;
  // @@protoc_insertion_point(class_scope:Schola.Point)
 private:
  class _Internal;
  void set_has_box_point();
  void set_has_discrete_point();
  void set_has_multi_discrete_point();
  void set_has_multi_binary_point();
  void set_has_dict_point();
  inline bool has_point() const;
  inline void clear_has_point();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 5,
                                   5, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Point& from_msg);
    union PointUnion {
      constexpr PointUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE box_point_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE discrete_point_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE multi_discrete_point_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE multi_binary_point_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE dict_point_;
    } point_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Points_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull Point_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BoxPoint

// repeated float values = 1;
inline int BoxPoint::_internal_values_size() const {
  return _internal_values().size();
}
inline int BoxPoint::values_size() const {
  return _internal_values_size();
}
inline void BoxPoint::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
}
inline float BoxPoint::values(int index) const {
  // @@protoc_insertion_point(field_get:Schola.BoxPoint.values)
  return _internal_values().Get(index);
}
inline void BoxPoint::set_values(int index, float value) {
  _internal_mutable_values()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.BoxPoint.values)
}
inline void BoxPoint::add_values(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_values()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.BoxPoint.values)
}
inline const ::google::protobuf::RepeatedField<float>& BoxPoint::values() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.BoxPoint.values)
  return _internal_values();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL BoxPoint::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.BoxPoint.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::google::protobuf::RepeatedField<float>&
BoxPoint::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
BoxPoint::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

// .Schola.DType dtype = 2;
inline void BoxPoint::clear_dtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::Schola::DType BoxPoint::dtype() const {
  // @@protoc_insertion_point(field_get:Schola.BoxPoint.dtype)
  return _internal_dtype();
}
inline void BoxPoint::set_dtype(::Schola::DType value) {
  _internal_set_dtype(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.BoxPoint.dtype)
}
inline ::Schola::DType BoxPoint::_internal_dtype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Schola::DType>(_impl_.dtype_);
}
inline void BoxPoint::_internal_set_dtype(::Schola::DType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtype_ = value;
}

// repeated int32 shape = 3;
inline int BoxPoint::_internal_shape_size() const {
  return _internal_shape().size();
}
inline int BoxPoint::shape_size() const {
  return _internal_shape_size();
}
inline void BoxPoint::clear_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_.Clear();
}
inline ::int32_t BoxPoint::shape(int index) const {
  // @@protoc_insertion_point(field_get:Schola.BoxPoint.shape)
  return _internal_shape().Get(index);
}
inline void BoxPoint::set_shape(int index, ::int32_t value) {
  _internal_mutable_shape()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.BoxPoint.shape)
}
inline void BoxPoint::add_shape(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_shape()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.BoxPoint.shape)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BoxPoint::shape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.BoxPoint.shape)
  return _internal_shape();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BoxPoint::mutable_shape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.BoxPoint.shape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_shape();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BoxPoint::_internal_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shape_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BoxPoint::_internal_mutable_shape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.shape_;
}

// -------------------------------------------------------------------

// DiscretePoint

// int32 value = 1;
inline void DiscretePoint::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t DiscretePoint::value() const {
  // @@protoc_insertion_point(field_get:Schola.DiscretePoint.value)
  return _internal_value();
}
inline void DiscretePoint::set_value(::int32_t value) {
  _internal_set_value(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.DiscretePoint.value)
}
inline ::int32_t DiscretePoint::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void DiscretePoint::_internal_set_value(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// -------------------------------------------------------------------

// MultiDiscretePoint

// repeated int32 values = 1;
inline int MultiDiscretePoint::_internal_values_size() const {
  return _internal_values().size();
}
inline int MultiDiscretePoint::values_size() const {
  return _internal_values_size();
}
inline void MultiDiscretePoint::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
}
inline ::int32_t MultiDiscretePoint::values(int index) const {
  // @@protoc_insertion_point(field_get:Schola.MultiDiscretePoint.values)
  return _internal_values().Get(index);
}
inline void MultiDiscretePoint::set_values(int index, ::int32_t value) {
  _internal_mutable_values()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.MultiDiscretePoint.values)
}
inline void MultiDiscretePoint::add_values(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_values()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.MultiDiscretePoint.values)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& MultiDiscretePoint::values() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.MultiDiscretePoint.values)
  return _internal_values();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL MultiDiscretePoint::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.MultiDiscretePoint.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
MultiDiscretePoint::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
MultiDiscretePoint::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

// -------------------------------------------------------------------

// MultiBinaryPoint

// repeated bool values = 1;
inline int MultiBinaryPoint::_internal_values_size() const {
  return _internal_values().size();
}
inline int MultiBinaryPoint::values_size() const {
  return _internal_values_size();
}
inline void MultiBinaryPoint::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
}
inline bool MultiBinaryPoint::values(int index) const {
  // @@protoc_insertion_point(field_get:Schola.MultiBinaryPoint.values)
  return _internal_values().Get(index);
}
inline void MultiBinaryPoint::set_values(int index, bool value) {
  _internal_mutable_values()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.MultiBinaryPoint.values)
}
inline void MultiBinaryPoint::add_values(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_values()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.MultiBinaryPoint.values)
}
inline const ::google::protobuf::RepeatedField<bool>& MultiBinaryPoint::values() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.MultiBinaryPoint.values)
  return _internal_values();
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL MultiBinaryPoint::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.MultiBinaryPoint.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::google::protobuf::RepeatedField<bool>&
MultiBinaryPoint::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL
MultiBinaryPoint::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DictPoint

// map<string, .Schola.Point> values = 1;
inline int DictPoint::_internal_values_size() const {
  return _internal_values().size();
}
inline int DictPoint::values_size() const {
  return _internal_values_size();
}
inline void DictPoint::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::Schola::Point>& DictPoint::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::Schola::Point>& DictPoint::values() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Schola.DictPoint.values)
  return _internal_values();
}
inline ::google::protobuf::Map<std::string, ::Schola::Point>* PROTOBUF_NONNULL DictPoint::_internal_mutable_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.values_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::Schola::Point>* PROTOBUF_NONNULL DictPoint::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Schola.DictPoint.values)
  return _internal_mutable_values();
}

// -------------------------------------------------------------------

// Point

// .Schola.BoxPoint box_point = 1;
inline bool Point::has_box_point() const {
  return point_case() == kBoxPoint;
}
inline bool Point::_internal_has_box_point() const {
  return point_case() == kBoxPoint;
}
inline void Point::set_has_box_point() {
  _impl_._oneof_case_[0] = kBoxPoint;
}
inline void Point::clear_box_point() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (point_case() == kBoxPoint) {
    if (GetArena() == nullptr) {
      delete _impl_.point_.box_point_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.point_.box_point_);
    }
    clear_has_point();
  }
}
inline ::Schola::BoxPoint* PROTOBUF_NULLABLE Point::release_box_point() {
  // @@protoc_insertion_point(field_release:Schola.Point.box_point)
  if (point_case() == kBoxPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::BoxPoint*>(_impl_.point_.box_point_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.point_.box_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::BoxPoint& Point::_internal_box_point() const {
  return point_case() == kBoxPoint ? *reinterpret_cast<::Schola::BoxPoint*>(_impl_.point_.box_point_) : reinterpret_cast<::Schola::BoxPoint&>(::Schola::_BoxPoint_default_instance_);
}
inline const ::Schola::BoxPoint& Point::box_point() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Point.box_point)
  return _internal_box_point();
}
inline ::Schola::BoxPoint* PROTOBUF_NULLABLE Point::unsafe_arena_release_box_point() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Point.box_point)
  if (point_case() == kBoxPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::BoxPoint*>(_impl_.point_.box_point_);
    _impl_.point_.box_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Point::unsafe_arena_set_allocated_box_point(
    ::Schola::BoxPoint* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_point();
  if (value) {
    set_has_box_point();
    _impl_.point_.box_point_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Point.box_point)
}
inline ::Schola::BoxPoint* PROTOBUF_NONNULL Point::_internal_mutable_box_point() {
  if (point_case() != kBoxPoint) {
    clear_point();
    set_has_box_point();
    _impl_.point_.box_point_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::BoxPoint>(GetArena()));
  }
  return reinterpret_cast<::Schola::BoxPoint*>(_impl_.point_.box_point_);
}
inline ::Schola::BoxPoint* PROTOBUF_NONNULL Point::mutable_box_point()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::BoxPoint* _msg = _internal_mutable_box_point();
  // @@protoc_insertion_point(field_mutable:Schola.Point.box_point)
  return _msg;
}

// .Schola.DiscretePoint discrete_point = 2;
inline bool Point::has_discrete_point() const {
  return point_case() == kDiscretePoint;
}
inline bool Point::_internal_has_discrete_point() const {
  return point_case() == kDiscretePoint;
}
inline void Point::set_has_discrete_point() {
  _impl_._oneof_case_[0] = kDiscretePoint;
}
inline void Point::clear_discrete_point() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (point_case() == kDiscretePoint) {
    if (GetArena() == nullptr) {
      delete _impl_.point_.discrete_point_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.point_.discrete_point_);
    }
    clear_has_point();
  }
}
inline ::Schola::DiscretePoint* PROTOBUF_NULLABLE Point::release_discrete_point() {
  // @@protoc_insertion_point(field_release:Schola.Point.discrete_point)
  if (point_case() == kDiscretePoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::DiscretePoint*>(_impl_.point_.discrete_point_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.point_.discrete_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::DiscretePoint& Point::_internal_discrete_point() const {
  return point_case() == kDiscretePoint ? *reinterpret_cast<::Schola::DiscretePoint*>(_impl_.point_.discrete_point_) : reinterpret_cast<::Schola::DiscretePoint&>(::Schola::_DiscretePoint_default_instance_);
}
inline const ::Schola::DiscretePoint& Point::discrete_point() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Point.discrete_point)
  return _internal_discrete_point();
}
inline ::Schola::DiscretePoint* PROTOBUF_NULLABLE Point::unsafe_arena_release_discrete_point() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Point.discrete_point)
  if (point_case() == kDiscretePoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::DiscretePoint*>(_impl_.point_.discrete_point_);
    _impl_.point_.discrete_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Point::unsafe_arena_set_allocated_discrete_point(
    ::Schola::DiscretePoint* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_point();
  if (value) {
    set_has_discrete_point();
    _impl_.point_.discrete_point_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Point.discrete_point)
}
inline ::Schola::DiscretePoint* PROTOBUF_NONNULL Point::_internal_mutable_discrete_point() {
  if (point_case() != kDiscretePoint) {
    clear_point();
    set_has_discrete_point();
    _impl_.point_.discrete_point_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::DiscretePoint>(GetArena()));
  }
  return reinterpret_cast<::Schola::DiscretePoint*>(_impl_.point_.discrete_point_);
}
inline ::Schola::DiscretePoint* PROTOBUF_NONNULL Point::mutable_discrete_point()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::DiscretePoint* _msg = _internal_mutable_discrete_point();
  // @@protoc_insertion_point(field_mutable:Schola.Point.discrete_point)
  return _msg;
}

// .Schola.MultiDiscretePoint multi_discrete_point = 3;
inline bool Point::has_multi_discrete_point() const {
  return point_case() == kMultiDiscretePoint;
}
inline bool Point::_internal_has_multi_discrete_point() const {
  return point_case() == kMultiDiscretePoint;
}
inline void Point::set_has_multi_discrete_point() {
  _impl_._oneof_case_[0] = kMultiDiscretePoint;
}
inline void Point::clear_multi_discrete_point() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (point_case() == kMultiDiscretePoint) {
    if (GetArena() == nullptr) {
      delete _impl_.point_.multi_discrete_point_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.point_.multi_discrete_point_);
    }
    clear_has_point();
  }
}
inline ::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE Point::release_multi_discrete_point() {
  // @@protoc_insertion_point(field_release:Schola.Point.multi_discrete_point)
  if (point_case() == kMultiDiscretePoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::MultiDiscretePoint*>(_impl_.point_.multi_discrete_point_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.point_.multi_discrete_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::MultiDiscretePoint& Point::_internal_multi_discrete_point() const {
  return point_case() == kMultiDiscretePoint ? *reinterpret_cast<::Schola::MultiDiscretePoint*>(_impl_.point_.multi_discrete_point_) : reinterpret_cast<::Schola::MultiDiscretePoint&>(::Schola::_MultiDiscretePoint_default_instance_);
}
inline const ::Schola::MultiDiscretePoint& Point::multi_discrete_point() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Point.multi_discrete_point)
  return _internal_multi_discrete_point();
}
inline ::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE Point::unsafe_arena_release_multi_discrete_point() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Point.multi_discrete_point)
  if (point_case() == kMultiDiscretePoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::MultiDiscretePoint*>(_impl_.point_.multi_discrete_point_);
    _impl_.point_.multi_discrete_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Point::unsafe_arena_set_allocated_multi_discrete_point(
    ::Schola::MultiDiscretePoint* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_point();
  if (value) {
    set_has_multi_discrete_point();
    _impl_.point_.multi_discrete_point_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Point.multi_discrete_point)
}
inline ::Schola::MultiDiscretePoint* PROTOBUF_NONNULL Point::_internal_mutable_multi_discrete_point() {
  if (point_case() != kMultiDiscretePoint) {
    clear_point();
    set_has_multi_discrete_point();
    _impl_.point_.multi_discrete_point_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::MultiDiscretePoint>(GetArena()));
  }
  return reinterpret_cast<::Schola::MultiDiscretePoint*>(_impl_.point_.multi_discrete_point_);
}
inline ::Schola::MultiDiscretePoint* PROTOBUF_NONNULL Point::mutable_multi_discrete_point()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::MultiDiscretePoint* _msg = _internal_mutable_multi_discrete_point();
  // @@protoc_insertion_point(field_mutable:Schola.Point.multi_discrete_point)
  return _msg;
}

// .Schola.MultiBinaryPoint multi_binary_point = 4;
inline bool Point::has_multi_binary_point() const {
  return point_case() == kMultiBinaryPoint;
}
inline bool Point::_internal_has_multi_binary_point() const {
  return point_case() == kMultiBinaryPoint;
}
inline void Point::set_has_multi_binary_point() {
  _impl_._oneof_case_[0] = kMultiBinaryPoint;
}
inline void Point::clear_multi_binary_point() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (point_case() == kMultiBinaryPoint) {
    if (GetArena() == nullptr) {
      delete _impl_.point_.multi_binary_point_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.point_.multi_binary_point_);
    }
    clear_has_point();
  }
}
inline ::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE Point::release_multi_binary_point() {
  // @@protoc_insertion_point(field_release:Schola.Point.multi_binary_point)
  if (point_case() == kMultiBinaryPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::MultiBinaryPoint*>(_impl_.point_.multi_binary_point_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.point_.multi_binary_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::MultiBinaryPoint& Point::_internal_multi_binary_point() const {
  return point_case() == kMultiBinaryPoint ? *reinterpret_cast<::Schola::MultiBinaryPoint*>(_impl_.point_.multi_binary_point_) : reinterpret_cast<::Schola::MultiBinaryPoint&>(::Schola::_MultiBinaryPoint_default_instance_);
}
inline const ::Schola::MultiBinaryPoint& Point::multi_binary_point() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Point.multi_binary_point)
  return _internal_multi_binary_point();
}
inline ::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE Point::unsafe_arena_release_multi_binary_point() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Point.multi_binary_point)
  if (point_case() == kMultiBinaryPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::MultiBinaryPoint*>(_impl_.point_.multi_binary_point_);
    _impl_.point_.multi_binary_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Point::unsafe_arena_set_allocated_multi_binary_point(
    ::Schola::MultiBinaryPoint* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_point();
  if (value) {
    set_has_multi_binary_point();
    _impl_.point_.multi_binary_point_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Point.multi_binary_point)
}
inline ::Schola::MultiBinaryPoint* PROTOBUF_NONNULL Point::_internal_mutable_multi_binary_point() {
  if (point_case() != kMultiBinaryPoint) {
    clear_point();
    set_has_multi_binary_point();
    _impl_.point_.multi_binary_point_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::MultiBinaryPoint>(GetArena()));
  }
  return reinterpret_cast<::Schola::MultiBinaryPoint*>(_impl_.point_.multi_binary_point_);
}
inline ::Schola::MultiBinaryPoint* PROTOBUF_NONNULL Point::mutable_multi_binary_point()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::MultiBinaryPoint* _msg = _internal_mutable_multi_binary_point();
  // @@protoc_insertion_point(field_mutable:Schola.Point.multi_binary_point)
  return _msg;
}

// .Schola.DictPoint dict_point = 5;
inline bool Point::has_dict_point() const {
  return point_case() == kDictPoint;
}
inline bool Point::_internal_has_dict_point() const {
  return point_case() == kDictPoint;
}
inline void Point::set_has_dict_point() {
  _impl_._oneof_case_[0] = kDictPoint;
}
inline void Point::clear_dict_point() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (point_case() == kDictPoint) {
    if (GetArena() == nullptr) {
      delete _impl_.point_.dict_point_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.point_.dict_point_);
    }
    clear_has_point();
  }
}
inline ::Schola::DictPoint* PROTOBUF_NULLABLE Point::release_dict_point() {
  // @@protoc_insertion_point(field_release:Schola.Point.dict_point)
  if (point_case() == kDictPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::DictPoint*>(_impl_.point_.dict_point_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.point_.dict_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::DictPoint& Point::_internal_dict_point() const {
  return point_case() == kDictPoint ? *reinterpret_cast<::Schola::DictPoint*>(_impl_.point_.dict_point_) : reinterpret_cast<::Schola::DictPoint&>(::Schola::_DictPoint_default_instance_);
}
inline const ::Schola::DictPoint& Point::dict_point() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Point.dict_point)
  return _internal_dict_point();
}
inline ::Schola::DictPoint* PROTOBUF_NULLABLE Point::unsafe_arena_release_dict_point() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Point.dict_point)
  if (point_case() == kDictPoint) {
    clear_has_point();
    auto* temp = reinterpret_cast<::Schola::DictPoint*>(_impl_.point_.dict_point_);
    _impl_.point_.dict_point_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Point::unsafe_arena_set_allocated_dict_point(
    ::Schola::DictPoint* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_point();
  if (value) {
    set_has_dict_point();
    _impl_.point_.dict_point_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Point.dict_point)
}
inline ::Schola::DictPoint* PROTOBUF_NONNULL Point::_internal_mutable_dict_point() {
  if (point_case() != kDictPoint) {
    clear_point();
    set_has_dict_point();
    _impl_.point_.dict_point_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::DictPoint>(GetArena()));
  }
  return reinterpret_cast<::Schola::DictPoint*>(_impl_.point_.dict_point_);
}
inline ::Schola::DictPoint* PROTOBUF_NONNULL Point::mutable_dict_point()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::DictPoint* _msg = _internal_mutable_dict_point();
  // @@protoc_insertion_point(field_mutable:Schola.Point.dict_point)
  return _msg;
}

inline bool Point::has_point() const {
  return point_case() != POINT_NOT_SET;
}
inline void Point::clear_has_point() {
  _impl_._oneof_case_[0] = POINT_NOT_SET;
}
inline Point::PointCase Point::point_case() const {
  return Point::PointCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // Points_2eproto_2epb_2eh
