// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Spaces.proto
// Protobuf C++ Version: 6.31.1

#ifndef Spaces_2eproto_2epb_2eh
#define Spaces_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "DType.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Spaces_2eproto SCHOLAPROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_Spaces_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Spaces_2eproto;
}  // extern "C"
namespace Schola {
class BoxSpace;
struct BoxSpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern BoxSpaceDefaultTypeInternal _BoxSpace_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxSpace_class_data_;
class BoxSpace_BoxSpaceDimension;
struct BoxSpace_BoxSpaceDimensionDefaultTypeInternal;
SCHOLAPROTOBUF_API extern BoxSpace_BoxSpaceDimensionDefaultTypeInternal _BoxSpace_BoxSpaceDimension_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxSpace_BoxSpaceDimension_class_data_;
class DictSpace;
struct DictSpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DictSpaceDefaultTypeInternal _DictSpace_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictSpace_class_data_;
class DictSpace_SpacesEntry_DoNotUse;
struct DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal _DictSpace_SpacesEntry_DoNotUse_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictSpace_SpacesEntry_DoNotUse_class_data_;
class DiscreteSpace;
struct DiscreteSpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern DiscreteSpaceDefaultTypeInternal _DiscreteSpace_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DiscreteSpace_class_data_;
class MultiBinarySpace;
struct MultiBinarySpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern MultiBinarySpaceDefaultTypeInternal _MultiBinarySpace_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiBinarySpace_class_data_;
class MultiDiscreteSpace;
struct MultiDiscreteSpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern MultiDiscreteSpaceDefaultTypeInternal _MultiDiscreteSpace_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiDiscreteSpace_class_data_;
class Space;
struct SpaceDefaultTypeInternal;
SCHOLAPROTOBUF_API extern SpaceDefaultTypeInternal _Space_default_instance_;
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull Space_class_data_;
}  // namespace Schola
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Schola {

// ===================================================================


// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API MultiDiscreteSpace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.MultiDiscreteSpace) */ {
 public:
  inline MultiDiscreteSpace() : MultiDiscreteSpace(nullptr) {}
  ~MultiDiscreteSpace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MultiDiscreteSpace* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MultiDiscreteSpace));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MultiDiscreteSpace(::google::protobuf::internal::ConstantInitialized);

  inline MultiDiscreteSpace(const MultiDiscreteSpace& from) : MultiDiscreteSpace(nullptr, from) {}
  inline MultiDiscreteSpace(MultiDiscreteSpace&& from) noexcept
      : MultiDiscreteSpace(nullptr, ::std::move(from)) {}
  inline MultiDiscreteSpace& operator=(const MultiDiscreteSpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiDiscreteSpace& operator=(MultiDiscreteSpace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiDiscreteSpace& default_instance() {
    return *reinterpret_cast<const MultiDiscreteSpace*>(
        &_MultiDiscreteSpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MultiDiscreteSpace& a, MultiDiscreteSpace& b) { a.Swap(&b); }
  inline void Swap(MultiDiscreteSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiDiscreteSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiDiscreteSpace* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MultiDiscreteSpace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MultiDiscreteSpace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MultiDiscreteSpace& from) { MultiDiscreteSpace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MultiDiscreteSpace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.MultiDiscreteSpace"; }

 protected:
  explicit MultiDiscreteSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MultiDiscreteSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MultiDiscreteSpace& from);
  MultiDiscreteSpace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MultiDiscreteSpace&& from) noexcept
      : MultiDiscreteSpace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHighFieldNumber = 1,
  };
  // repeated int32 high = 1;
  int high_size() const;
  private:
  int _internal_high_size() const;

  public:
  void clear_high() ;
  ::int32_t high(int index) const;
  void set_high(int index, ::int32_t value);
  void add_high(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& high() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_high();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_high() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_high();

  public:
  // @@protoc_insertion_point(class_scope:Schola.MultiDiscreteSpace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MultiDiscreteSpace& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> high_;
    ::google::protobuf::internal::CachedSize _high_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiDiscreteSpace_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API MultiBinarySpace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.MultiBinarySpace) */ {
 public:
  inline MultiBinarySpace() : MultiBinarySpace(nullptr) {}
  ~MultiBinarySpace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MultiBinarySpace* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MultiBinarySpace));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MultiBinarySpace(::google::protobuf::internal::ConstantInitialized);

  inline MultiBinarySpace(const MultiBinarySpace& from) : MultiBinarySpace(nullptr, from) {}
  inline MultiBinarySpace(MultiBinarySpace&& from) noexcept
      : MultiBinarySpace(nullptr, ::std::move(from)) {}
  inline MultiBinarySpace& operator=(const MultiBinarySpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiBinarySpace& operator=(MultiBinarySpace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiBinarySpace& default_instance() {
    return *reinterpret_cast<const MultiBinarySpace*>(
        &_MultiBinarySpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(MultiBinarySpace& a, MultiBinarySpace& b) { a.Swap(&b); }
  inline void Swap(MultiBinarySpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiBinarySpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiBinarySpace* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MultiBinarySpace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MultiBinarySpace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MultiBinarySpace& from) { MultiBinarySpace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MultiBinarySpace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.MultiBinarySpace"; }

 protected:
  explicit MultiBinarySpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MultiBinarySpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MultiBinarySpace& from);
  MultiBinarySpace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MultiBinarySpace&& from) noexcept
      : MultiBinarySpace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kShapeFieldNumber = 1,
  };
  // int32 shape = 1;
  void clear_shape() ;
  ::int32_t shape() const;
  void set_shape(::int32_t value);

  private:
  ::int32_t _internal_shape() const;
  void _internal_set_shape(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.MultiBinarySpace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MultiBinarySpace& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t shape_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull MultiBinarySpace_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API DiscreteSpace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.DiscreteSpace) */ {
 public:
  inline DiscreteSpace() : DiscreteSpace(nullptr) {}
  ~DiscreteSpace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiscreteSpace* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiscreteSpace));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiscreteSpace(::google::protobuf::internal::ConstantInitialized);

  inline DiscreteSpace(const DiscreteSpace& from) : DiscreteSpace(nullptr, from) {}
  inline DiscreteSpace(DiscreteSpace&& from) noexcept
      : DiscreteSpace(nullptr, ::std::move(from)) {}
  inline DiscreteSpace& operator=(const DiscreteSpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiscreteSpace& operator=(DiscreteSpace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiscreteSpace& default_instance() {
    return *reinterpret_cast<const DiscreteSpace*>(
        &_DiscreteSpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DiscreteSpace& a, DiscreteSpace& b) { a.Swap(&b); }
  inline void Swap(DiscreteSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiscreteSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiscreteSpace* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiscreteSpace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiscreteSpace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiscreteSpace& from) { DiscreteSpace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiscreteSpace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.DiscreteSpace"; }

 protected:
  explicit DiscreteSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DiscreteSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiscreteSpace& from);
  DiscreteSpace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DiscreteSpace&& from) noexcept
      : DiscreteSpace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHighFieldNumber = 1,
  };
  // int32 high = 1;
  void clear_high() ;
  ::int32_t high() const;
  void set_high(::int32_t value);

  private:
  ::int32_t _internal_high() const;
  void _internal_set_high(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.DiscreteSpace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DiscreteSpace& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t high_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DiscreteSpace_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API BoxSpace_BoxSpaceDimension final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.BoxSpace.BoxSpaceDimension) */ {
 public:
  inline BoxSpace_BoxSpaceDimension() : BoxSpace_BoxSpaceDimension(nullptr) {}
  ~BoxSpace_BoxSpaceDimension() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoxSpace_BoxSpaceDimension));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoxSpace_BoxSpaceDimension(::google::protobuf::internal::ConstantInitialized);

  inline BoxSpace_BoxSpaceDimension(const BoxSpace_BoxSpaceDimension& from) : BoxSpace_BoxSpaceDimension(nullptr, from) {}
  inline BoxSpace_BoxSpaceDimension(BoxSpace_BoxSpaceDimension&& from) noexcept
      : BoxSpace_BoxSpaceDimension(nullptr, ::std::move(from)) {}
  inline BoxSpace_BoxSpaceDimension& operator=(const BoxSpace_BoxSpaceDimension& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoxSpace_BoxSpaceDimension& operator=(BoxSpace_BoxSpaceDimension&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BoxSpace_BoxSpaceDimension& default_instance() {
    return *reinterpret_cast<const BoxSpace_BoxSpaceDimension*>(
        &_BoxSpace_BoxSpaceDimension_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BoxSpace_BoxSpaceDimension& a, BoxSpace_BoxSpaceDimension& b) { a.Swap(&b); }
  inline void Swap(BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BoxSpace_BoxSpaceDimension>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BoxSpace_BoxSpaceDimension& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BoxSpace_BoxSpaceDimension& from) { BoxSpace_BoxSpaceDimension::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.BoxSpace.BoxSpaceDimension"; }

 protected:
  explicit BoxSpace_BoxSpaceDimension(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BoxSpace_BoxSpaceDimension(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoxSpace_BoxSpaceDimension& from);
  BoxSpace_BoxSpaceDimension(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BoxSpace_BoxSpaceDimension&& from) noexcept
      : BoxSpace_BoxSpaceDimension(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLowFieldNumber = 1,
    kHighFieldNumber = 2,
  };
  // float low = 1;
  void clear_low() ;
  float low() const;
  void set_low(float value);

  private:
  float _internal_low() const;
  void _internal_set_low(float value);

  public:
  // float high = 2;
  void clear_high() ;
  float high() const;
  void set_high(float value);

  private:
  float _internal_high() const;
  void _internal_set_high(float value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.BoxSpace.BoxSpaceDimension)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BoxSpace_BoxSpaceDimension& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float low_;
    float high_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxSpace_BoxSpaceDimension_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API BoxSpace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.BoxSpace) */ {
 public:
  inline BoxSpace() : BoxSpace(nullptr) {}
  ~BoxSpace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoxSpace* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoxSpace));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoxSpace(::google::protobuf::internal::ConstantInitialized);

  inline BoxSpace(const BoxSpace& from) : BoxSpace(nullptr, from) {}
  inline BoxSpace(BoxSpace&& from) noexcept
      : BoxSpace(nullptr, ::std::move(from)) {}
  inline BoxSpace& operator=(const BoxSpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoxSpace& operator=(BoxSpace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BoxSpace& default_instance() {
    return *reinterpret_cast<const BoxSpace*>(
        &_BoxSpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BoxSpace& a, BoxSpace& b) { a.Swap(&b); }
  inline void Swap(BoxSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoxSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoxSpace* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BoxSpace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BoxSpace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BoxSpace& from) { BoxSpace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoxSpace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.BoxSpace"; }

 protected:
  explicit BoxSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BoxSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoxSpace& from);
  BoxSpace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BoxSpace&& from) noexcept
      : BoxSpace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using BoxSpaceDimension = BoxSpace_BoxSpaceDimension;

  // accessors -------------------------------------------------------
  enum : int {
    kDimensionsFieldNumber = 1,
    kShapeDimensionsFieldNumber = 2,
    kDtypeFieldNumber = 3,
  };
  // repeated .Schola.BoxSpace.BoxSpaceDimension dimensions = 1;
  int dimensions_size() const;
  private:
  int _internal_dimensions_size() const;

  public:
  void clear_dimensions() ;
  ::Schola::BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL mutable_dimensions(int index);
  ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>* PROTOBUF_NONNULL mutable_dimensions();

  private:
  const ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>& _internal_dimensions() const;
  ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>* PROTOBUF_NONNULL _internal_mutable_dimensions();
  public:
  const ::Schola::BoxSpace_BoxSpaceDimension& dimensions(int index) const;
  ::Schola::BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL add_dimensions();
  const ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>& dimensions() const;
  // repeated int32 shape_dimensions = 2;
  int shape_dimensions_size() const;
  private:
  int _internal_shape_dimensions_size() const;

  public:
  void clear_shape_dimensions() ;
  ::int32_t shape_dimensions(int index) const;
  void set_shape_dimensions(int index, ::int32_t value);
  void add_shape_dimensions(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& shape_dimensions() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_shape_dimensions();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_shape_dimensions() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_shape_dimensions();

  public:
  // .Schola.DType dtype = 3;
  void clear_dtype() ;
  ::Schola::DType dtype() const;
  void set_dtype(::Schola::DType value);

  private:
  ::Schola::DType _internal_dtype() const;
  void _internal_set_dtype(::Schola::DType value);

  public:
  // @@protoc_insertion_point(class_scope:Schola.BoxSpace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BoxSpace& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Schola::BoxSpace_BoxSpaceDimension > dimensions_;
    ::google::protobuf::RepeatedField<::int32_t> shape_dimensions_;
    ::google::protobuf::internal::CachedSize _shape_dimensions_cached_byte_size_;
    int dtype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull BoxSpace_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API DictSpace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.DictSpace) */ {
 public:
  inline DictSpace() : DictSpace(nullptr) {}
  ~DictSpace() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DictSpace* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DictSpace));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DictSpace(::google::protobuf::internal::ConstantInitialized);

  inline DictSpace(const DictSpace& from) : DictSpace(nullptr, from) {}
  inline DictSpace(DictSpace&& from) noexcept
      : DictSpace(nullptr, ::std::move(from)) {}
  inline DictSpace& operator=(const DictSpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline DictSpace& operator=(DictSpace&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DictSpace& default_instance() {
    return *reinterpret_cast<const DictSpace*>(
        &_DictSpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(DictSpace& a, DictSpace& b) { a.Swap(&b); }
  inline void Swap(DictSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DictSpace* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DictSpace* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DictSpace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DictSpace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DictSpace& from) { DictSpace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DictSpace* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.DictSpace"; }

 protected:
  explicit DictSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DictSpace(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DictSpace& from);
  DictSpace(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DictSpace&& from) noexcept
      : DictSpace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSpacesFieldNumber = 1,
  };
  // map<string, .Schola.Space> spaces = 1;
  int spaces_size() const;
  private:
  int _internal_spaces_size() const;

  public:
  void clear_spaces() ;
  const ::google::protobuf::Map<std::string, ::Schola::Space>& spaces() const;
  ::google::protobuf::Map<std::string, ::Schola::Space>* PROTOBUF_NONNULL mutable_spaces();

  private:
  const ::google::protobuf::Map<std::string, ::Schola::Space>& _internal_spaces() const;
  ::google::protobuf::Map<std::string, ::Schola::Space>* PROTOBUF_NONNULL _internal_mutable_spaces();

  public:
  // @@protoc_insertion_point(class_scope:Schola.DictSpace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DictSpace& from_msg);
    ::google::protobuf::internal::MapField<DictSpace_SpacesEntry_DoNotUse, std::string, ::Schola::Space,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        spaces_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictSpace_class_data_;
// -------------------------------------------------------------------

class DictSpace_SpacesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  DictSpace_SpacesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DictSpace_SpacesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit DictSpace_SpacesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_DictSpace_SpacesEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_Spaces_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 40,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull DictSpace_SpacesEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API Space final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Schola.Space) */ {
 public:
  inline Space() : Space(nullptr) {}
  ~Space() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Space* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Space));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Space(::google::protobuf::internal::ConstantInitialized);

  inline Space(const Space& from) : Space(nullptr, from) {}
  inline Space(Space&& from) noexcept
      : Space(nullptr, ::std::move(from)) {}
  inline Space& operator=(const Space& from) {
    CopyFrom(from);
    return *this;
  }
  inline Space& operator=(Space&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Space& default_instance() {
    return *reinterpret_cast<const Space*>(
        &_Space_default_instance_);
  }
  enum SpaceCase {
    kBoxSpace = 1,
    kDiscreteSpace = 2,
    kMultiDiscreteSpace = 3,
    kMultiBinarySpace = 4,
    kDictSpace = 5,
    SPACE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(Space& a, Space& b) { a.Swap(&b); }
  inline void Swap(Space* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Space* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Space* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Space>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Space& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Space& from) { Space::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Space* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Schola.Space"; }

 protected:
  explicit Space(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Space(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Space& from);
  Space(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Space&& from) noexcept
      : Space(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBoxSpaceFieldNumber = 1,
    kDiscreteSpaceFieldNumber = 2,
    kMultiDiscreteSpaceFieldNumber = 3,
    kMultiBinarySpaceFieldNumber = 4,
    kDictSpaceFieldNumber = 5,
  };
  // .Schola.BoxSpace box_space = 1;
  bool has_box_space() const;
  private:
  bool _internal_has_box_space() const;

  public:
  void clear_box_space() ;
  const ::Schola::BoxSpace& box_space() const;
  [[nodiscard]] ::Schola::BoxSpace* PROTOBUF_NULLABLE release_box_space();
  ::Schola::BoxSpace* PROTOBUF_NONNULL mutable_box_space();
  void set_allocated_box_space(::Schola::BoxSpace* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_box_space(::Schola::BoxSpace* PROTOBUF_NULLABLE value);
  ::Schola::BoxSpace* PROTOBUF_NULLABLE unsafe_arena_release_box_space();

  private:
  const ::Schola::BoxSpace& _internal_box_space() const;
  ::Schola::BoxSpace* PROTOBUF_NONNULL _internal_mutable_box_space();

  public:
  // .Schola.DiscreteSpace discrete_space = 2;
  bool has_discrete_space() const;
  private:
  bool _internal_has_discrete_space() const;

  public:
  void clear_discrete_space() ;
  const ::Schola::DiscreteSpace& discrete_space() const;
  [[nodiscard]] ::Schola::DiscreteSpace* PROTOBUF_NULLABLE release_discrete_space();
  ::Schola::DiscreteSpace* PROTOBUF_NONNULL mutable_discrete_space();
  void set_allocated_discrete_space(::Schola::DiscreteSpace* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_discrete_space(::Schola::DiscreteSpace* PROTOBUF_NULLABLE value);
  ::Schola::DiscreteSpace* PROTOBUF_NULLABLE unsafe_arena_release_discrete_space();

  private:
  const ::Schola::DiscreteSpace& _internal_discrete_space() const;
  ::Schola::DiscreteSpace* PROTOBUF_NONNULL _internal_mutable_discrete_space();

  public:
  // .Schola.MultiDiscreteSpace multi_discrete_space = 3;
  bool has_multi_discrete_space() const;
  private:
  bool _internal_has_multi_discrete_space() const;

  public:
  void clear_multi_discrete_space() ;
  const ::Schola::MultiDiscreteSpace& multi_discrete_space() const;
  [[nodiscard]] ::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE release_multi_discrete_space();
  ::Schola::MultiDiscreteSpace* PROTOBUF_NONNULL mutable_multi_discrete_space();
  void set_allocated_multi_discrete_space(::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_multi_discrete_space(::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE value);
  ::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE unsafe_arena_release_multi_discrete_space();

  private:
  const ::Schola::MultiDiscreteSpace& _internal_multi_discrete_space() const;
  ::Schola::MultiDiscreteSpace* PROTOBUF_NONNULL _internal_mutable_multi_discrete_space();

  public:
  // .Schola.MultiBinarySpace multi_binary_space = 4;
  bool has_multi_binary_space() const;
  private:
  bool _internal_has_multi_binary_space() const;

  public:
  void clear_multi_binary_space() ;
  const ::Schola::MultiBinarySpace& multi_binary_space() const;
  [[nodiscard]] ::Schola::MultiBinarySpace* PROTOBUF_NULLABLE release_multi_binary_space();
  ::Schola::MultiBinarySpace* PROTOBUF_NONNULL mutable_multi_binary_space();
  void set_allocated_multi_binary_space(::Schola::MultiBinarySpace* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_multi_binary_space(::Schola::MultiBinarySpace* PROTOBUF_NULLABLE value);
  ::Schola::MultiBinarySpace* PROTOBUF_NULLABLE unsafe_arena_release_multi_binary_space();

  private:
  const ::Schola::MultiBinarySpace& _internal_multi_binary_space() const;
  ::Schola::MultiBinarySpace* PROTOBUF_NONNULL _internal_mutable_multi_binary_space();

  public:
  // .Schola.DictSpace dict_space = 5;
  bool has_dict_space() const;
  private:
  bool _internal_has_dict_space() const;

  public:
  void clear_dict_space() ;
  const ::Schola::DictSpace& dict_space() const;
  [[nodiscard]] ::Schola::DictSpace* PROTOBUF_NULLABLE release_dict_space();
  ::Schola::DictSpace* PROTOBUF_NONNULL mutable_dict_space();
  void set_allocated_dict_space(::Schola::DictSpace* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_dict_space(::Schola::DictSpace* PROTOBUF_NULLABLE value);
  ::Schola::DictSpace* PROTOBUF_NULLABLE unsafe_arena_release_dict_space();

  private:
  const ::Schola::DictSpace& _internal_dict_space() const;
  ::Schola::DictSpace* PROTOBUF_NONNULL _internal_mutable_dict_space();

  public:
  void clear_space();
  SpaceCase space_case() const;
  // @@protoc_insertion_point(class_scope:Schola.Space)
 private:
  class _Internal;
  void set_has_box_space();
  void set_has_discrete_space();
  void set_has_multi_discrete_space();
  void set_has_multi_binary_space();
  void set_has_dict_space();
  inline bool has_space() const;
  inline void clear_has_space();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 5,
                                   5, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Space& from_msg);
    union SpaceUnion {
      constexpr SpaceUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE box_space_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE discrete_space_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE multi_discrete_space_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE multi_binary_space_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE dict_space_;
    } space_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Spaces_2eproto;
};

SCHOLAPROTOBUF_API extern const ::google::protobuf::internal::ClassDataFull Space_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BoxSpace_BoxSpaceDimension

// float low = 1;
inline void BoxSpace_BoxSpaceDimension::clear_low() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float BoxSpace_BoxSpaceDimension::low() const {
  // @@protoc_insertion_point(field_get:Schola.BoxSpace.BoxSpaceDimension.low)
  return _internal_low();
}
inline void BoxSpace_BoxSpaceDimension::set_low(float value) {
  _internal_set_low(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.BoxSpace.BoxSpaceDimension.low)
}
inline float BoxSpace_BoxSpaceDimension::_internal_low() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.low_;
}
inline void BoxSpace_BoxSpaceDimension::_internal_set_low(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_ = value;
}

// float high = 2;
inline void BoxSpace_BoxSpaceDimension::clear_high() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float BoxSpace_BoxSpaceDimension::high() const {
  // @@protoc_insertion_point(field_get:Schola.BoxSpace.BoxSpaceDimension.high)
  return _internal_high();
}
inline void BoxSpace_BoxSpaceDimension::set_high(float value) {
  _internal_set_high(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:Schola.BoxSpace.BoxSpaceDimension.high)
}
inline float BoxSpace_BoxSpaceDimension::_internal_high() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.high_;
}
inline void BoxSpace_BoxSpaceDimension::_internal_set_high(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = value;
}

// -------------------------------------------------------------------

// BoxSpace

// repeated .Schola.BoxSpace.BoxSpaceDimension dimensions = 1;
inline int BoxSpace::_internal_dimensions_size() const {
  return _internal_dimensions().size();
}
inline int BoxSpace::dimensions_size() const {
  return _internal_dimensions_size();
}
inline void BoxSpace::clear_dimensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dimensions_.Clear();
}
inline ::Schola::BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL BoxSpace::mutable_dimensions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Schola.BoxSpace.dimensions)
  return _internal_mutable_dimensions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>* PROTOBUF_NONNULL BoxSpace::mutable_dimensions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.BoxSpace.dimensions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_dimensions();
}
inline const ::Schola::BoxSpace_BoxSpaceDimension& BoxSpace::dimensions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.BoxSpace.dimensions)
  return _internal_dimensions().Get(index);
}
inline ::Schola::BoxSpace_BoxSpaceDimension* PROTOBUF_NONNULL BoxSpace::add_dimensions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Schola::BoxSpace_BoxSpaceDimension* _add = _internal_mutable_dimensions()->Add();
  // @@protoc_insertion_point(field_add:Schola.BoxSpace.dimensions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>& BoxSpace::dimensions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.BoxSpace.dimensions)
  return _internal_dimensions();
}
inline const ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>&
BoxSpace::_internal_dimensions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dimensions_;
}
inline ::google::protobuf::RepeatedPtrField<::Schola::BoxSpace_BoxSpaceDimension>* PROTOBUF_NONNULL
BoxSpace::_internal_mutable_dimensions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.dimensions_;
}

// repeated int32 shape_dimensions = 2;
inline int BoxSpace::_internal_shape_dimensions_size() const {
  return _internal_shape_dimensions().size();
}
inline int BoxSpace::shape_dimensions_size() const {
  return _internal_shape_dimensions_size();
}
inline void BoxSpace::clear_shape_dimensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_dimensions_.Clear();
}
inline ::int32_t BoxSpace::shape_dimensions(int index) const {
  // @@protoc_insertion_point(field_get:Schola.BoxSpace.shape_dimensions)
  return _internal_shape_dimensions().Get(index);
}
inline void BoxSpace::set_shape_dimensions(int index, ::int32_t value) {
  _internal_mutable_shape_dimensions()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.BoxSpace.shape_dimensions)
}
inline void BoxSpace::add_shape_dimensions(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_shape_dimensions()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.BoxSpace.shape_dimensions)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BoxSpace::shape_dimensions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.BoxSpace.shape_dimensions)
  return _internal_shape_dimensions();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BoxSpace::mutable_shape_dimensions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.BoxSpace.shape_dimensions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_shape_dimensions();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BoxSpace::_internal_shape_dimensions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shape_dimensions_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BoxSpace::_internal_mutable_shape_dimensions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.shape_dimensions_;
}

// .Schola.DType dtype = 3;
inline void BoxSpace::clear_dtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::Schola::DType BoxSpace::dtype() const {
  // @@protoc_insertion_point(field_get:Schola.BoxSpace.dtype)
  return _internal_dtype();
}
inline void BoxSpace::set_dtype(::Schola::DType value) {
  _internal_set_dtype(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.BoxSpace.dtype)
}
inline ::Schola::DType BoxSpace::_internal_dtype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Schola::DType>(_impl_.dtype_);
}
inline void BoxSpace::_internal_set_dtype(::Schola::DType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtype_ = value;
}

// -------------------------------------------------------------------

// DiscreteSpace

// int32 high = 1;
inline void DiscreteSpace::clear_high() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t DiscreteSpace::high() const {
  // @@protoc_insertion_point(field_get:Schola.DiscreteSpace.high)
  return _internal_high();
}
inline void DiscreteSpace::set_high(::int32_t value) {
  _internal_set_high(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.DiscreteSpace.high)
}
inline ::int32_t DiscreteSpace::_internal_high() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.high_;
}
inline void DiscreteSpace::_internal_set_high(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = value;
}

// -------------------------------------------------------------------

// MultiDiscreteSpace

// repeated int32 high = 1;
inline int MultiDiscreteSpace::_internal_high_size() const {
  return _internal_high().size();
}
inline int MultiDiscreteSpace::high_size() const {
  return _internal_high_size();
}
inline void MultiDiscreteSpace::clear_high() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_.Clear();
}
inline ::int32_t MultiDiscreteSpace::high(int index) const {
  // @@protoc_insertion_point(field_get:Schola.MultiDiscreteSpace.high)
  return _internal_high().Get(index);
}
inline void MultiDiscreteSpace::set_high(int index, ::int32_t value) {
  _internal_mutable_high()->Set(index, value);
  // @@protoc_insertion_point(field_set:Schola.MultiDiscreteSpace.high)
}
inline void MultiDiscreteSpace::add_high(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_high()->Add(value);
  // @@protoc_insertion_point(field_add:Schola.MultiDiscreteSpace.high)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& MultiDiscreteSpace::high() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Schola.MultiDiscreteSpace.high)
  return _internal_high();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL MultiDiscreteSpace::mutable_high()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Schola.MultiDiscreteSpace.high)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_high();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
MultiDiscreteSpace::_internal_high() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.high_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
MultiDiscreteSpace::_internal_mutable_high() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.high_;
}

// -------------------------------------------------------------------

// MultiBinarySpace

// int32 shape = 1;
inline void MultiBinarySpace::clear_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t MultiBinarySpace::shape() const {
  // @@protoc_insertion_point(field_get:Schola.MultiBinarySpace.shape)
  return _internal_shape();
}
inline void MultiBinarySpace::set_shape(::int32_t value) {
  _internal_set_shape(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Schola.MultiBinarySpace.shape)
}
inline ::int32_t MultiBinarySpace::_internal_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shape_;
}
inline void MultiBinarySpace::_internal_set_shape(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shape_ = value;
}

// -------------------------------------------------------------------

// Space

// .Schola.BoxSpace box_space = 1;
inline bool Space::has_box_space() const {
  return space_case() == kBoxSpace;
}
inline bool Space::_internal_has_box_space() const {
  return space_case() == kBoxSpace;
}
inline void Space::set_has_box_space() {
  _impl_._oneof_case_[0] = kBoxSpace;
}
inline void Space::clear_box_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (space_case() == kBoxSpace) {
    if (GetArena() == nullptr) {
      delete _impl_.space_.box_space_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.space_.box_space_);
    }
    clear_has_space();
  }
}
inline ::Schola::BoxSpace* PROTOBUF_NULLABLE Space::release_box_space() {
  // @@protoc_insertion_point(field_release:Schola.Space.box_space)
  if (space_case() == kBoxSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::BoxSpace*>(_impl_.space_.box_space_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.space_.box_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::BoxSpace& Space::_internal_box_space() const {
  return space_case() == kBoxSpace ? *reinterpret_cast<::Schola::BoxSpace*>(_impl_.space_.box_space_) : reinterpret_cast<::Schola::BoxSpace&>(::Schola::_BoxSpace_default_instance_);
}
inline const ::Schola::BoxSpace& Space::box_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Space.box_space)
  return _internal_box_space();
}
inline ::Schola::BoxSpace* PROTOBUF_NULLABLE Space::unsafe_arena_release_box_space() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Space.box_space)
  if (space_case() == kBoxSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::BoxSpace*>(_impl_.space_.box_space_);
    _impl_.space_.box_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Space::unsafe_arena_set_allocated_box_space(
    ::Schola::BoxSpace* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_space();
  if (value) {
    set_has_box_space();
    _impl_.space_.box_space_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Space.box_space)
}
inline ::Schola::BoxSpace* PROTOBUF_NONNULL Space::_internal_mutable_box_space() {
  if (space_case() != kBoxSpace) {
    clear_space();
    set_has_box_space();
    _impl_.space_.box_space_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::BoxSpace>(GetArena()));
  }
  return reinterpret_cast<::Schola::BoxSpace*>(_impl_.space_.box_space_);
}
inline ::Schola::BoxSpace* PROTOBUF_NONNULL Space::mutable_box_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::BoxSpace* _msg = _internal_mutable_box_space();
  // @@protoc_insertion_point(field_mutable:Schola.Space.box_space)
  return _msg;
}

// .Schola.DiscreteSpace discrete_space = 2;
inline bool Space::has_discrete_space() const {
  return space_case() == kDiscreteSpace;
}
inline bool Space::_internal_has_discrete_space() const {
  return space_case() == kDiscreteSpace;
}
inline void Space::set_has_discrete_space() {
  _impl_._oneof_case_[0] = kDiscreteSpace;
}
inline void Space::clear_discrete_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (space_case() == kDiscreteSpace) {
    if (GetArena() == nullptr) {
      delete _impl_.space_.discrete_space_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.space_.discrete_space_);
    }
    clear_has_space();
  }
}
inline ::Schola::DiscreteSpace* PROTOBUF_NULLABLE Space::release_discrete_space() {
  // @@protoc_insertion_point(field_release:Schola.Space.discrete_space)
  if (space_case() == kDiscreteSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::DiscreteSpace*>(_impl_.space_.discrete_space_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.space_.discrete_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::DiscreteSpace& Space::_internal_discrete_space() const {
  return space_case() == kDiscreteSpace ? *reinterpret_cast<::Schola::DiscreteSpace*>(_impl_.space_.discrete_space_) : reinterpret_cast<::Schola::DiscreteSpace&>(::Schola::_DiscreteSpace_default_instance_);
}
inline const ::Schola::DiscreteSpace& Space::discrete_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Space.discrete_space)
  return _internal_discrete_space();
}
inline ::Schola::DiscreteSpace* PROTOBUF_NULLABLE Space::unsafe_arena_release_discrete_space() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Space.discrete_space)
  if (space_case() == kDiscreteSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::DiscreteSpace*>(_impl_.space_.discrete_space_);
    _impl_.space_.discrete_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Space::unsafe_arena_set_allocated_discrete_space(
    ::Schola::DiscreteSpace* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_space();
  if (value) {
    set_has_discrete_space();
    _impl_.space_.discrete_space_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Space.discrete_space)
}
inline ::Schola::DiscreteSpace* PROTOBUF_NONNULL Space::_internal_mutable_discrete_space() {
  if (space_case() != kDiscreteSpace) {
    clear_space();
    set_has_discrete_space();
    _impl_.space_.discrete_space_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::DiscreteSpace>(GetArena()));
  }
  return reinterpret_cast<::Schola::DiscreteSpace*>(_impl_.space_.discrete_space_);
}
inline ::Schola::DiscreteSpace* PROTOBUF_NONNULL Space::mutable_discrete_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::DiscreteSpace* _msg = _internal_mutable_discrete_space();
  // @@protoc_insertion_point(field_mutable:Schola.Space.discrete_space)
  return _msg;
}

// .Schola.MultiDiscreteSpace multi_discrete_space = 3;
inline bool Space::has_multi_discrete_space() const {
  return space_case() == kMultiDiscreteSpace;
}
inline bool Space::_internal_has_multi_discrete_space() const {
  return space_case() == kMultiDiscreteSpace;
}
inline void Space::set_has_multi_discrete_space() {
  _impl_._oneof_case_[0] = kMultiDiscreteSpace;
}
inline void Space::clear_multi_discrete_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (space_case() == kMultiDiscreteSpace) {
    if (GetArena() == nullptr) {
      delete _impl_.space_.multi_discrete_space_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.space_.multi_discrete_space_);
    }
    clear_has_space();
  }
}
inline ::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE Space::release_multi_discrete_space() {
  // @@protoc_insertion_point(field_release:Schola.Space.multi_discrete_space)
  if (space_case() == kMultiDiscreteSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::MultiDiscreteSpace*>(_impl_.space_.multi_discrete_space_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.space_.multi_discrete_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::MultiDiscreteSpace& Space::_internal_multi_discrete_space() const {
  return space_case() == kMultiDiscreteSpace ? *reinterpret_cast<::Schola::MultiDiscreteSpace*>(_impl_.space_.multi_discrete_space_) : reinterpret_cast<::Schola::MultiDiscreteSpace&>(::Schola::_MultiDiscreteSpace_default_instance_);
}
inline const ::Schola::MultiDiscreteSpace& Space::multi_discrete_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Space.multi_discrete_space)
  return _internal_multi_discrete_space();
}
inline ::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE Space::unsafe_arena_release_multi_discrete_space() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Space.multi_discrete_space)
  if (space_case() == kMultiDiscreteSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::MultiDiscreteSpace*>(_impl_.space_.multi_discrete_space_);
    _impl_.space_.multi_discrete_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Space::unsafe_arena_set_allocated_multi_discrete_space(
    ::Schola::MultiDiscreteSpace* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_space();
  if (value) {
    set_has_multi_discrete_space();
    _impl_.space_.multi_discrete_space_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Space.multi_discrete_space)
}
inline ::Schola::MultiDiscreteSpace* PROTOBUF_NONNULL Space::_internal_mutable_multi_discrete_space() {
  if (space_case() != kMultiDiscreteSpace) {
    clear_space();
    set_has_multi_discrete_space();
    _impl_.space_.multi_discrete_space_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::MultiDiscreteSpace>(GetArena()));
  }
  return reinterpret_cast<::Schola::MultiDiscreteSpace*>(_impl_.space_.multi_discrete_space_);
}
inline ::Schola::MultiDiscreteSpace* PROTOBUF_NONNULL Space::mutable_multi_discrete_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::MultiDiscreteSpace* _msg = _internal_mutable_multi_discrete_space();
  // @@protoc_insertion_point(field_mutable:Schola.Space.multi_discrete_space)
  return _msg;
}

// .Schola.MultiBinarySpace multi_binary_space = 4;
inline bool Space::has_multi_binary_space() const {
  return space_case() == kMultiBinarySpace;
}
inline bool Space::_internal_has_multi_binary_space() const {
  return space_case() == kMultiBinarySpace;
}
inline void Space::set_has_multi_binary_space() {
  _impl_._oneof_case_[0] = kMultiBinarySpace;
}
inline void Space::clear_multi_binary_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (space_case() == kMultiBinarySpace) {
    if (GetArena() == nullptr) {
      delete _impl_.space_.multi_binary_space_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.space_.multi_binary_space_);
    }
    clear_has_space();
  }
}
inline ::Schola::MultiBinarySpace* PROTOBUF_NULLABLE Space::release_multi_binary_space() {
  // @@protoc_insertion_point(field_release:Schola.Space.multi_binary_space)
  if (space_case() == kMultiBinarySpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::MultiBinarySpace*>(_impl_.space_.multi_binary_space_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.space_.multi_binary_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::MultiBinarySpace& Space::_internal_multi_binary_space() const {
  return space_case() == kMultiBinarySpace ? *reinterpret_cast<::Schola::MultiBinarySpace*>(_impl_.space_.multi_binary_space_) : reinterpret_cast<::Schola::MultiBinarySpace&>(::Schola::_MultiBinarySpace_default_instance_);
}
inline const ::Schola::MultiBinarySpace& Space::multi_binary_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Space.multi_binary_space)
  return _internal_multi_binary_space();
}
inline ::Schola::MultiBinarySpace* PROTOBUF_NULLABLE Space::unsafe_arena_release_multi_binary_space() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Space.multi_binary_space)
  if (space_case() == kMultiBinarySpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::MultiBinarySpace*>(_impl_.space_.multi_binary_space_);
    _impl_.space_.multi_binary_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Space::unsafe_arena_set_allocated_multi_binary_space(
    ::Schola::MultiBinarySpace* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_space();
  if (value) {
    set_has_multi_binary_space();
    _impl_.space_.multi_binary_space_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Space.multi_binary_space)
}
inline ::Schola::MultiBinarySpace* PROTOBUF_NONNULL Space::_internal_mutable_multi_binary_space() {
  if (space_case() != kMultiBinarySpace) {
    clear_space();
    set_has_multi_binary_space();
    _impl_.space_.multi_binary_space_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::MultiBinarySpace>(GetArena()));
  }
  return reinterpret_cast<::Schola::MultiBinarySpace*>(_impl_.space_.multi_binary_space_);
}
inline ::Schola::MultiBinarySpace* PROTOBUF_NONNULL Space::mutable_multi_binary_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::MultiBinarySpace* _msg = _internal_mutable_multi_binary_space();
  // @@protoc_insertion_point(field_mutable:Schola.Space.multi_binary_space)
  return _msg;
}

// .Schola.DictSpace dict_space = 5;
inline bool Space::has_dict_space() const {
  return space_case() == kDictSpace;
}
inline bool Space::_internal_has_dict_space() const {
  return space_case() == kDictSpace;
}
inline void Space::set_has_dict_space() {
  _impl_._oneof_case_[0] = kDictSpace;
}
inline void Space::clear_dict_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (space_case() == kDictSpace) {
    if (GetArena() == nullptr) {
      delete _impl_.space_.dict_space_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.space_.dict_space_);
    }
    clear_has_space();
  }
}
inline ::Schola::DictSpace* PROTOBUF_NULLABLE Space::release_dict_space() {
  // @@protoc_insertion_point(field_release:Schola.Space.dict_space)
  if (space_case() == kDictSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::DictSpace*>(_impl_.space_.dict_space_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.space_.dict_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::DictSpace& Space::_internal_dict_space() const {
  return space_case() == kDictSpace ? *reinterpret_cast<::Schola::DictSpace*>(_impl_.space_.dict_space_) : reinterpret_cast<::Schola::DictSpace&>(::Schola::_DictSpace_default_instance_);
}
inline const ::Schola::DictSpace& Space::dict_space() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Schola.Space.dict_space)
  return _internal_dict_space();
}
inline ::Schola::DictSpace* PROTOBUF_NULLABLE Space::unsafe_arena_release_dict_space() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.Space.dict_space)
  if (space_case() == kDictSpace) {
    clear_has_space();
    auto* temp = reinterpret_cast<::Schola::DictSpace*>(_impl_.space_.dict_space_);
    _impl_.space_.dict_space_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Space::unsafe_arena_set_allocated_dict_space(
    ::Schola::DictSpace* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_space();
  if (value) {
    set_has_dict_space();
    _impl_.space_.dict_space_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.Space.dict_space)
}
inline ::Schola::DictSpace* PROTOBUF_NONNULL Space::_internal_mutable_dict_space() {
  if (space_case() != kDictSpace) {
    clear_space();
    set_has_dict_space();
    _impl_.space_.dict_space_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Schola::DictSpace>(GetArena()));
  }
  return reinterpret_cast<::Schola::DictSpace*>(_impl_.space_.dict_space_);
}
inline ::Schola::DictSpace* PROTOBUF_NONNULL Space::mutable_dict_space()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Schola::DictSpace* _msg = _internal_mutable_dict_space();
  // @@protoc_insertion_point(field_mutable:Schola.Space.dict_space)
  return _msg;
}

inline bool Space::has_space() const {
  return space_case() != SPACE_NOT_SET;
}
inline void Space::clear_has_space() {
  _impl_._oneof_case_[0] = SPACE_NOT_SET;
}
inline Space::SpaceCase Space::space_case() const {
  return Space::SpaceCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DictSpace

// map<string, .Schola.Space> spaces = 1;
inline int DictSpace::_internal_spaces_size() const {
  return _internal_spaces().size();
}
inline int DictSpace::spaces_size() const {
  return _internal_spaces_size();
}
inline void DictSpace::clear_spaces() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spaces_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::Schola::Space>& DictSpace::_internal_spaces() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spaces_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::Schola::Space>& DictSpace::spaces() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Schola.DictSpace.spaces)
  return _internal_spaces();
}
inline ::google::protobuf::Map<std::string, ::Schola::Space>* PROTOBUF_NONNULL DictSpace::_internal_mutable_spaces() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.spaces_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::Schola::Space>* PROTOBUF_NONNULL DictSpace::mutable_spaces()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Schola.DictSpace.spaces)
  return _internal_mutable_spaces();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END

#endif  // Spaces_2eproto_2epb_2eh
