// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StateUpdates.proto
// Protobuf C++ Version: 6.31.1

#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#pragma warning (disable : 4073)
#include "StateUpdates.pb.h"

#include <algorithm>
#include <type_traits>
#include "HAL/Platform.h"

THIRD_PARTY_INCLUDES_START
#include "ScholaProtobufMacroGuardBegin.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Schola {
template <typename>
PROTOBUF_CONSTEXPR EnvironmentSettings_OptionsEntry_DoNotUse::EnvironmentSettings_OptionsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : EnvironmentSettings_OptionsEntry_DoNotUse::MapEntry(EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : EnvironmentSettings_OptionsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EnvironmentSettings_OptionsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentSettings_OptionsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentSettings_OptionsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    EnvironmentSettings_OptionsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentSettings_OptionsEntry_DoNotUseDefaultTypeInternal _EnvironmentSettings_OptionsEntry_DoNotUse_default_instance_;

inline constexpr EnvironmentSettings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : options_{},
        optional_seed_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR EnvironmentSettings::EnvironmentSettings(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EnvironmentSettings_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnvironmentSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentSettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentSettingsDefaultTypeInternal() {}
  union {
    EnvironmentSettings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentSettingsDefaultTypeInternal _EnvironmentSettings_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR Reset_EnvironmentsEntry_DoNotUse::Reset_EnvironmentsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Reset_EnvironmentsEntry_DoNotUse::MapEntry(Reset_EnvironmentsEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Reset_EnvironmentsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Reset_EnvironmentsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reset_EnvironmentsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reset_EnvironmentsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Reset_EnvironmentsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reset_EnvironmentsEntry_DoNotUseDefaultTypeInternal _Reset_EnvironmentsEntry_DoNotUse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR EnvironmentStep_UpdatesEntry_DoNotUse::EnvironmentStep_UpdatesEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : EnvironmentStep_UpdatesEntry_DoNotUse::MapEntry(EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : EnvironmentStep_UpdatesEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EnvironmentStep_UpdatesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentStep_UpdatesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentStep_UpdatesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    EnvironmentStep_UpdatesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentStep_UpdatesEntry_DoNotUseDefaultTypeInternal _EnvironmentStep_UpdatesEntry_DoNotUse_default_instance_;

inline constexpr Reset::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : environments_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Reset::Reset(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Reset_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResetDefaultTypeInternal() {}
  union {
    Reset _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResetDefaultTypeInternal _Reset_default_instance_;

inline constexpr EnvironmentStep::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : updates_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EnvironmentStep::EnvironmentStep(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EnvironmentStep_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnvironmentStepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentStepDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentStepDefaultTypeInternal() {}
  union {
    EnvironmentStep _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentStepDefaultTypeInternal _EnvironmentStep_default_instance_;

inline constexpr Step::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : environments_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Step::Step(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Step_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StepDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StepDefaultTypeInternal() {}
  union {
    Step _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StepDefaultTypeInternal _Step_default_instance_;

inline constexpr StateUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{static_cast< ::Schola::CommunicatorStatus >(0)},
        update_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR StateUpdate::StateUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(StateUpdate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StateUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateUpdateDefaultTypeInternal() {}
  union {
    StateUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SCHOLAPROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateUpdateDefaultTypeInternal _StateUpdate_default_instance_;
}  // namespace Schola
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_StateUpdates_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_StateUpdates_2eproto = nullptr;
const ::uint32_t
    TableStruct_StateUpdates_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentStep_UpdatesEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentStep, _impl_.updates_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings_OptionsEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings, _impl_._oneof_case_[0]),
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings, _impl_.options_),
        PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings, _impl_.optional_seed_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::Reset_EnvironmentsEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Schola::Reset_EnvironmentsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Schola::Reset_EnvironmentsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::Reset, _impl_.environments_),
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::Step, _impl_.environments_),
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::Schola::StateUpdate, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Schola::StateUpdate, _impl_._oneof_case_[0]),
        8, // hasbit index offset
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Schola::StateUpdate, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::Schola::StateUpdate, _impl_.update_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Schola::EnvironmentStep_UpdatesEntry_DoNotUse)},
        {7, sizeof(::Schola::EnvironmentStep)},
        {9, sizeof(::Schola::EnvironmentSettings_OptionsEntry_DoNotUse)},
        {16, sizeof(::Schola::EnvironmentSettings)},
        {21, sizeof(::Schola::Reset_EnvironmentsEntry_DoNotUse)},
        {28, sizeof(::Schola::Reset)},
        {30, sizeof(::Schola::Step)},
        {32, sizeof(::Schola::StateUpdate)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Schola::_EnvironmentStep_UpdatesEntry_DoNotUse_default_instance_._instance,
    &::Schola::_EnvironmentStep_default_instance_._instance,
    &::Schola::_EnvironmentSettings_OptionsEntry_DoNotUse_default_instance_._instance,
    &::Schola::_EnvironmentSettings_default_instance_._instance,
    &::Schola::_Reset_EnvironmentsEntry_DoNotUse_default_instance_._instance,
    &::Schola::_Reset_default_instance_._instance,
    &::Schola::_Step_default_instance_._instance,
    &::Schola::_StateUpdate_default_instance_._instance,
};
const char descriptor_table_protodef_StateUpdates_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022StateUpdates.proto\022\006Schola\032\014Points.pro"
    "to\"\207\001\n\017EnvironmentStep\0225\n\007updates\030\001 \003(\0132"
    "$.Schola.EnvironmentStep.UpdatesEntry\032=\n"
    "\014UpdatesEntry\022\013\n\003key\030\001 \001(\t\022\034\n\005value\030\002 \001("
    "\0132\r.Schola.Point:\0028\001\"\241\001\n\023EnvironmentSett"
    "ings\022\016\n\004seed\030\001 \001(\005H\000\0229\n\007options\030\002 \003(\0132(."
    "Schola.EnvironmentSettings.OptionsEntry\032"
    ".\n\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
    "\001(\t:\0028\001B\017\n\roptional_seed\"\220\001\n\005Reset\0225\n\014en"
    "vironments\030\001 \003(\0132\037.Schola.Reset.Environm"
    "entsEntry\032P\n\021EnvironmentsEntry\022\013\n\003key\030\001 "
    "\001(\005\022*\n\005value\030\002 \001(\0132\033.Schola.EnvironmentS"
    "ettings:\0028\001\"5\n\004Step\022-\n\014environments\030\001 \003("
    "\0132\027.Schola.EnvironmentStep\"\201\001\n\013StateUpda"
    "te\022\036\n\005reset\030\001 \001(\0132\r.Schola.ResetH\000\022\034\n\004st"
    "ep\030\002 \001(\0132\014.Schola.StepH\000\022*\n\006status\030\003 \001(\016"
    "2\032.Schola.CommunicatorStatusB\010\n\006update*5"
    "\n\022CommunicatorStatus\022\010\n\004GOOD\020\000\022\t\n\005ERROR\020"
    "\001\022\n\n\006CLOSED\020\002b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_StateUpdates_2eproto_deps[1] = {
        &::descriptor_table_Points_2eproto,
};
static ::absl::once_flag descriptor_table_StateUpdates_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_StateUpdates_2eproto = {
    false,
    false,
    741,
    descriptor_table_protodef_StateUpdates_2eproto,
    "StateUpdates.proto",
    &descriptor_table_StateUpdates_2eproto_once,
    descriptor_table_StateUpdates_2eproto_deps,
    1,
    8,
    schemas,
    file_default_instances,
    TableStruct_StateUpdates_2eproto::offsets,
    file_level_enum_descriptors_StateUpdates_2eproto,
    file_level_service_descriptors_StateUpdates_2eproto,
};
namespace Schola {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CommunicatorStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_StateUpdates_2eproto);
  return file_level_enum_descriptors_StateUpdates_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommunicatorStatus_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
EnvironmentStep_UpdatesEntry_DoNotUse::EnvironmentStep_UpdatesEntry_DoNotUse()
    : SuperType(EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.base()) {}
EnvironmentStep_UpdatesEntry_DoNotUse::EnvironmentStep_UpdatesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
EnvironmentStep_UpdatesEntry_DoNotUse::EnvironmentStep_UpdatesEntry_DoNotUse() : SuperType() {}
EnvironmentStep_UpdatesEntry_DoNotUse::EnvironmentStep_UpdatesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL EnvironmentStep_UpdatesEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentStep_UpdatesEntry_DoNotUse(arena);
}
constexpr auto EnvironmentStep_UpdatesEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EnvironmentStep_UpdatesEntry_DoNotUse),
                                            alignof(EnvironmentStep_UpdatesEntry_DoNotUse));
}
constexpr auto EnvironmentStep_UpdatesEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentStep_UpdatesEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentStep_UpdatesEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentStep_UpdatesEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentStep_UpdatesEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&EnvironmentStep_UpdatesEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &EnvironmentStep_UpdatesEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentStep_UpdatesEntry_DoNotUse_class_data_ =
        EnvironmentStep_UpdatesEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentStep_UpdatesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentStep_UpdatesEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.tc_table);
  return EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 47, 2>
EnvironmentStep_UpdatesEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EnvironmentStep_UpdatesEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::EnvironmentStep_UpdatesEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Schola.Point value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Schola.Point value = 2;
    {PROTOBUF_FIELD_OFFSET(EnvironmentStep_UpdatesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Schola::Point>()},
  }},
  {{
    "\43\3\0\0\0\0\0\0"
    "Schola.EnvironmentStep.UpdatesEntry"
    "key"
  }},
};
// ===================================================================

class EnvironmentStep::_Internal {
 public:
};

void EnvironmentStep::clear_updates() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.updates_.Clear();
}
EnvironmentStep::EnvironmentStep(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentStep_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Schola.EnvironmentStep)
}
PROTOBUF_NDEBUG_INLINE EnvironmentStep::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Schola::EnvironmentStep& from_msg)
      : updates_{visibility, arena, from.updates_},
        _cached_size_{0} {}

EnvironmentStep::EnvironmentStep(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EnvironmentStep& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentStep_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EnvironmentStep* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Schola.EnvironmentStep)
}
PROTOBUF_NDEBUG_INLINE EnvironmentStep::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : updates_{visibility, arena},
        _cached_size_{0} {}

inline void EnvironmentStep::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EnvironmentStep::~EnvironmentStep() {
  // @@protoc_insertion_point(destructor:Schola.EnvironmentStep)
  SharedDtor(*this);
}
inline void EnvironmentStep::SharedDtor(MessageLite& self) {
  EnvironmentStep& this_ = static_cast<EnvironmentStep&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EnvironmentStep::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentStep(arena);
}
constexpr auto EnvironmentStep::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EnvironmentStep, _impl_.updates_) +
          decltype(EnvironmentStep::_impl_.updates_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(EnvironmentStep, _impl_.updates_) +
          decltype(EnvironmentStep::_impl_.updates_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(EnvironmentStep), alignof(EnvironmentStep), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EnvironmentStep::PlacementNew_,
                                 sizeof(EnvironmentStep),
                                 alignof(EnvironmentStep));
  }
}
constexpr auto EnvironmentStep::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentStep_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentStep::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentStep>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentStep::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EnvironmentStep>(), &EnvironmentStep::ByteSizeLong,
              &EnvironmentStep::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentStep, _impl_._cached_size_),
          false,
      },
      &EnvironmentStep::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentStep_class_data_ =
        EnvironmentStep::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentStep::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentStep_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentStep_class_data_.tc_table);
  return EnvironmentStep_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 38, 2>
EnvironmentStep::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EnvironmentStep_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::EnvironmentStep>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, .Schola.Point> updates = 1;
    {PROTOBUF_FIELD_OFFSET(EnvironmentStep, _impl_.updates_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(1, 0, 0,
                                       9, 11,
                                       0)},
      {::_pbi::TcParser::GetTable<::Schola::Point>()},
  }},
  {{
    "\26\7\0\0\0\0\0\0"
    "Schola.EnvironmentStep"
    "updates"
  }},
};
PROTOBUF_NOINLINE void EnvironmentStep::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.EnvironmentStep)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.updates_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EnvironmentStep::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EnvironmentStep& this_ = static_cast<const EnvironmentStep&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EnvironmentStep::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EnvironmentStep& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Schola.EnvironmentStep)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<string, .Schola.Point> updates = 1;
  if (!this_._internal_updates().empty()) {
    using MapType = ::google::protobuf::Map<std::string, ::Schola::Point>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, ::Schola::Point,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = this_._internal_updates();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentStep.updates");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentStep.updates");
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.EnvironmentStep)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EnvironmentStep::ByteSizeLong(const MessageLite& base) {
  const EnvironmentStep& this_ = static_cast<const EnvironmentStep&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EnvironmentStep::ByteSizeLong() const {
  const EnvironmentStep& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Schola.EnvironmentStep)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // map<string, .Schola.Point> updates = 1;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_updates_size());
      for (const auto& entry : this_._internal_updates()) {
        total_size += _pbi::MapEntryFuncs<std::string, ::Schola::Point,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EnvironmentStep::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnvironmentStep*>(&to_msg);
  auto& from = static_cast<const EnvironmentStep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.EnvironmentStep)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.updates_.MergeFrom(from._impl_.updates_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnvironmentStep::CopyFrom(const EnvironmentStep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.EnvironmentStep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnvironmentStep::InternalSwap(EnvironmentStep* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.updates_.InternalSwap(&other->_impl_.updates_);
}

::google::protobuf::Metadata EnvironmentStep::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
EnvironmentSettings_OptionsEntry_DoNotUse::EnvironmentSettings_OptionsEntry_DoNotUse()
    : SuperType(EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.base()) {}
EnvironmentSettings_OptionsEntry_DoNotUse::EnvironmentSettings_OptionsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
EnvironmentSettings_OptionsEntry_DoNotUse::EnvironmentSettings_OptionsEntry_DoNotUse() : SuperType() {}
EnvironmentSettings_OptionsEntry_DoNotUse::EnvironmentSettings_OptionsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL EnvironmentSettings_OptionsEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentSettings_OptionsEntry_DoNotUse(arena);
}
constexpr auto EnvironmentSettings_OptionsEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EnvironmentSettings_OptionsEntry_DoNotUse),
                                            alignof(EnvironmentSettings_OptionsEntry_DoNotUse));
}
constexpr auto EnvironmentSettings_OptionsEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentSettings_OptionsEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentSettings_OptionsEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentSettings_OptionsEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentSettings_OptionsEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&EnvironmentSettings_OptionsEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &EnvironmentSettings_OptionsEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentSettings_OptionsEntry_DoNotUse_class_data_ =
        EnvironmentSettings_OptionsEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentSettings_OptionsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentSettings_OptionsEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.tc_table);
  return EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 56, 2>
EnvironmentSettings_OptionsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EnvironmentSettings_OptionsEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::EnvironmentSettings_OptionsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(EnvironmentSettings_OptionsEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\3\5\0\0\0\0\0"
    "Schola.EnvironmentSettings.OptionsEntry"
    "key"
    "value"
  }},
};
// ===================================================================

class EnvironmentSettings::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentSettings, _impl_._oneof_case_);
};

EnvironmentSettings::EnvironmentSettings(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentSettings_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Schola.EnvironmentSettings)
}
PROTOBUF_NDEBUG_INLINE EnvironmentSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Schola::EnvironmentSettings& from_msg)
      : options_{visibility, arena, from.options_},
        optional_seed_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

EnvironmentSettings::EnvironmentSettings(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EnvironmentSettings& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentSettings_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EnvironmentSettings* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (optional_seed_case()) {
    case OPTIONAL_SEED_NOT_SET:
      break;
      case kSeed:
        _impl_.optional_seed_.seed_ = from._impl_.optional_seed_.seed_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Schola.EnvironmentSettings)
}
PROTOBUF_NDEBUG_INLINE EnvironmentSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : options_{visibility, arena},
        optional_seed_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void EnvironmentSettings::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EnvironmentSettings::~EnvironmentSettings() {
  // @@protoc_insertion_point(destructor:Schola.EnvironmentSettings)
  SharedDtor(*this);
}
inline void EnvironmentSettings::SharedDtor(MessageLite& self) {
  EnvironmentSettings& this_ = static_cast<EnvironmentSettings&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_optional_seed()) {
    this_.clear_optional_seed();
  }
  this_._impl_.~Impl_();
}

void EnvironmentSettings::clear_optional_seed() {
// @@protoc_insertion_point(one_of_clear_start:Schola.EnvironmentSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (optional_seed_case()) {
    case kSeed: {
      // No need to clear
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = OPTIONAL_SEED_NOT_SET;
}


inline void* PROTOBUF_NONNULL EnvironmentSettings::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentSettings(arena);
}
constexpr auto EnvironmentSettings::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EnvironmentSettings, _impl_.options_) +
          decltype(EnvironmentSettings::_impl_.options_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(EnvironmentSettings, _impl_.options_) +
          decltype(EnvironmentSettings::_impl_.options_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(EnvironmentSettings), alignof(EnvironmentSettings), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EnvironmentSettings::PlacementNew_,
                                 sizeof(EnvironmentSettings),
                                 alignof(EnvironmentSettings));
  }
}
constexpr auto EnvironmentSettings::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentSettings_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentSettings::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentSettings>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentSettings::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EnvironmentSettings>(), &EnvironmentSettings::ByteSizeLong,
              &EnvironmentSettings::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentSettings, _impl_._cached_size_),
          false,
      },
      &EnvironmentSettings::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentSettings_class_data_ =
        EnvironmentSettings::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentSettings::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentSettings_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentSettings_class_data_.tc_table);
  return EnvironmentSettings_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 42, 2>
EnvironmentSettings::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EnvironmentSettings_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::EnvironmentSettings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 seed = 1;
    {PROTOBUF_FIELD_OFFSET(EnvironmentSettings, _impl_.optional_seed_.seed_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // map<string, string> options = 2;
    {PROTOBUF_FIELD_OFFSET(EnvironmentSettings, _impl_.options_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(1, 0, 0,
                                       9, 9,
                                       0)},
  }},
  {{
    "\32\0\7\0\0\0\0\0"
    "Schola.EnvironmentSettings"
    "options"
  }},
};
PROTOBUF_NOINLINE void EnvironmentSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.EnvironmentSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.options_.Clear();
  clear_optional_seed();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EnvironmentSettings::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EnvironmentSettings& this_ = static_cast<const EnvironmentSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EnvironmentSettings::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EnvironmentSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Schola.EnvironmentSettings)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 seed = 1;
  if (this_.optional_seed_case() == kSeed) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_seed(), target);
  }

  // map<string, string> options = 2;
  if (!this_._internal_options().empty()) {
    using MapType = ::google::protobuf::Map<std::string, std::string>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>;
    const auto& field = this_._internal_options();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentSettings.options");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentSettings.options");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentSettings.options");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Schola.EnvironmentSettings.options");
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.EnvironmentSettings)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EnvironmentSettings::ByteSizeLong(const MessageLite& base) {
  const EnvironmentSettings& this_ = static_cast<const EnvironmentSettings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EnvironmentSettings::ByteSizeLong() const {
  const EnvironmentSettings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Schola.EnvironmentSettings)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // map<string, string> options = 2;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_options_size());
      for (const auto& entry : this_._internal_options()) {
        total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  switch (this_.optional_seed_case()) {
    // int32 seed = 1;
    case kSeed: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_seed());
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EnvironmentSettings::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnvironmentSettings*>(&to_msg);
  auto& from = static_cast<const EnvironmentSettings&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.EnvironmentSettings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.options_.MergeFrom(from._impl_.options_);
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_optional_seed();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSeed: {
        _this->_impl_.optional_seed_.seed_ = from._impl_.optional_seed_.seed_;
        break;
      }
      case OPTIONAL_SEED_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnvironmentSettings::CopyFrom(const EnvironmentSettings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.EnvironmentSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnvironmentSettings::InternalSwap(EnvironmentSettings* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.options_.InternalSwap(&other->_impl_.options_);
  swap(_impl_.optional_seed_, other->_impl_.optional_seed_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata EnvironmentSettings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
Reset_EnvironmentsEntry_DoNotUse::Reset_EnvironmentsEntry_DoNotUse()
    : SuperType(Reset_EnvironmentsEntry_DoNotUse_class_data_.base()) {}
Reset_EnvironmentsEntry_DoNotUse::Reset_EnvironmentsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, Reset_EnvironmentsEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
Reset_EnvironmentsEntry_DoNotUse::Reset_EnvironmentsEntry_DoNotUse() : SuperType() {}
Reset_EnvironmentsEntry_DoNotUse::Reset_EnvironmentsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL Reset_EnvironmentsEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Reset_EnvironmentsEntry_DoNotUse(arena);
}
constexpr auto Reset_EnvironmentsEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Reset_EnvironmentsEntry_DoNotUse),
                                            alignof(Reset_EnvironmentsEntry_DoNotUse));
}
constexpr auto Reset_EnvironmentsEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Reset_EnvironmentsEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Reset_EnvironmentsEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Reset_EnvironmentsEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Reset_EnvironmentsEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&Reset_EnvironmentsEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &Reset_EnvironmentsEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Reset_EnvironmentsEntry_DoNotUse_class_data_ =
        Reset_EnvironmentsEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Reset_EnvironmentsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Reset_EnvironmentsEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Reset_EnvironmentsEntry_DoNotUse_class_data_.tc_table);
  return Reset_EnvironmentsEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
Reset_EnvironmentsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Reset_EnvironmentsEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::Reset_EnvironmentsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Schola.EnvironmentSettings value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Reset_EnvironmentsEntry_DoNotUse, _impl_.key_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .Schola.EnvironmentSettings value = 2;
    {PROTOBUF_FIELD_OFFSET(Reset_EnvironmentsEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Schola::EnvironmentSettings>()},
  }},
  {{
  }},
};
// ===================================================================

class Reset::_Internal {
 public:
};

Reset::Reset(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reset_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Schola.Reset)
}
PROTOBUF_NDEBUG_INLINE Reset::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Schola::Reset& from_msg)
      : environments_{visibility, arena, from.environments_},
        _cached_size_{0} {}

Reset::Reset(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Reset& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reset_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Reset* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Schola.Reset)
}
PROTOBUF_NDEBUG_INLINE Reset::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : environments_{visibility, arena},
        _cached_size_{0} {}

inline void Reset::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Reset::~Reset() {
  // @@protoc_insertion_point(destructor:Schola.Reset)
  SharedDtor(*this);
}
inline void Reset::SharedDtor(MessageLite& self) {
  Reset& this_ = static_cast<Reset&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Reset::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Reset(arena);
}
constexpr auto Reset::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Reset, _impl_.environments_) +
          decltype(Reset::_impl_.environments_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Reset, _impl_.environments_) +
          decltype(Reset::_impl_.environments_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Reset), alignof(Reset), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Reset::PlacementNew_,
                                 sizeof(Reset),
                                 alignof(Reset));
  }
}
constexpr auto Reset::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Reset_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Reset::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Reset>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Reset::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Reset>(), &Reset::ByteSizeLong,
              &Reset::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Reset, _impl_._cached_size_),
          false,
      },
      &Reset::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Reset_class_data_ =
        Reset::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Reset::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Reset_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Reset_class_data_.tc_table);
  return Reset_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2>
Reset::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Reset_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::Reset>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int32, .Schola.EnvironmentSettings> environments = 1;
    {PROTOBUF_FIELD_OFFSET(Reset, _impl_.environments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(0, 0, 0,
                                       5, 11,
                                       0)},
      {::_pbi::TcParser::GetTable<::Schola::EnvironmentSettings>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Reset::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.Reset)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environments_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Reset::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Reset& this_ = static_cast<const Reset&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Reset::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Reset& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Schola.Reset)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<int32, .Schola.EnvironmentSettings> environments = 1;
  if (!this_._internal_environments().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::Schola::EnvironmentSettings>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::Schola::EnvironmentSettings,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = this_._internal_environments();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.Reset)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Reset::ByteSizeLong(const MessageLite& base) {
  const Reset& this_ = static_cast<const Reset&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Reset::ByteSizeLong() const {
  const Reset& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Schola.Reset)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // map<int32, .Schola.EnvironmentSettings> environments = 1;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_environments_size());
      for (const auto& entry : this_._internal_environments()) {
        total_size += _pbi::MapEntryFuncs<::int32_t, ::Schola::EnvironmentSettings,
                                       _pbi::WireFormatLite::TYPE_INT32,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Reset::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Reset*>(&to_msg);
  auto& from = static_cast<const Reset&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.Reset)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.environments_.MergeFrom(from._impl_.environments_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Reset::CopyFrom(const Reset& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.Reset)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Reset::InternalSwap(Reset* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.environments_.InternalSwap(&other->_impl_.environments_);
}

::google::protobuf::Metadata Reset::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Step::_Internal {
 public:
};

Step::Step(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Step_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Schola.Step)
}
PROTOBUF_NDEBUG_INLINE Step::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Schola::Step& from_msg)
      : environments_{visibility, arena, from.environments_},
        _cached_size_{0} {}

Step::Step(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Step& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Step_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Step* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Schola.Step)
}
PROTOBUF_NDEBUG_INLINE Step::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : environments_{visibility, arena},
        _cached_size_{0} {}

inline void Step::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Step::~Step() {
  // @@protoc_insertion_point(destructor:Schola.Step)
  SharedDtor(*this);
}
inline void Step::SharedDtor(MessageLite& self) {
  Step& this_ = static_cast<Step&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Step::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Step(arena);
}
constexpr auto Step::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Step, _impl_.environments_) +
          decltype(Step::_impl_.environments_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Step), alignof(Step), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Step::PlacementNew_,
                                 sizeof(Step),
                                 alignof(Step));
  }
}
constexpr auto Step::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Step_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Step::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Step>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Step::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Step>(), &Step::ByteSizeLong,
              &Step::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Step, _impl_._cached_size_),
          false,
      },
      &Step::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Step_class_data_ =
        Step::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Step::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Step_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Step_class_data_.tc_table);
  return Step_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
Step::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Step_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::Step>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Schola.EnvironmentStep environments = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Step, _impl_.environments_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .Schola.EnvironmentStep environments = 1;
    {PROTOBUF_FIELD_OFFSET(Step, _impl_.environments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Schola::EnvironmentStep>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Step::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.Step)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environments_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Step::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Step& this_ = static_cast<const Step&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Step::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Step& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Schola.Step)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .Schola.EnvironmentStep environments = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_environments_size());
       i < n; i++) {
    const auto& repfield = this_._internal_environments().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.Step)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Step::ByteSizeLong(const MessageLite& base) {
  const Step& this_ = static_cast<const Step&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Step::ByteSizeLong() const {
  const Step& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Schola.Step)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .Schola.EnvironmentStep environments = 1;
    {
      total_size += 1UL * this_._internal_environments_size();
      for (const auto& msg : this_._internal_environments()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Step::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Step*>(&to_msg);
  auto& from = static_cast<const Step&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.Step)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_environments()->MergeFrom(
      from._internal_environments());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Step::CopyFrom(const Step& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.Step)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Step::InternalSwap(Step* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.environments_.InternalSwap(&other->_impl_.environments_);
}

::google::protobuf::Metadata Step::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StateUpdate::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<StateUpdate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Schola::StateUpdate, _impl_._oneof_case_);
};

void StateUpdate::set_allocated_reset(::Schola::Reset* PROTOBUF_NULLABLE reset) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_update();
  if (reset) {
    ::google::protobuf::Arena* submessage_arena = reset->GetArena();
    if (message_arena != submessage_arena) {
      reset = ::google::protobuf::internal::GetOwnedMessage(message_arena, reset, submessage_arena);
    }
    set_has_reset();
    _impl_.update_.reset_ = reset;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.StateUpdate.reset)
}
void StateUpdate::set_allocated_step(::Schola::Step* PROTOBUF_NULLABLE step) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_update();
  if (step) {
    ::google::protobuf::Arena* submessage_arena = step->GetArena();
    if (message_arena != submessage_arena) {
      step = ::google::protobuf::internal::GetOwnedMessage(message_arena, step, submessage_arena);
    }
    set_has_step();
    _impl_.update_.step_ = step;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.StateUpdate.step)
}
StateUpdate::StateUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StateUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Schola.StateUpdate)
}
PROTOBUF_NDEBUG_INLINE StateUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Schola::StateUpdate& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        update_{},
        _oneof_case_{from._oneof_case_[0]} {}

StateUpdate::StateUpdate(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const StateUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StateUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StateUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;
  switch (update_case()) {
    case UPDATE_NOT_SET:
      break;
      case kReset:
        _impl_.update_.reset_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.update_.reset_);
        break;
      case kStep:
        _impl_.update_.step_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.update_.step_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Schola.StateUpdate)
}
PROTOBUF_NDEBUG_INLINE StateUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        update_{},
        _oneof_case_{} {}

inline void StateUpdate::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
StateUpdate::~StateUpdate() {
  // @@protoc_insertion_point(destructor:Schola.StateUpdate)
  SharedDtor(*this);
}
inline void StateUpdate::SharedDtor(MessageLite& self) {
  StateUpdate& this_ = static_cast<StateUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_update()) {
    this_.clear_update();
  }
  this_._impl_.~Impl_();
}

void StateUpdate::clear_update() {
// @@protoc_insertion_point(one_of_clear_start:Schola.StateUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (update_case()) {
    case kReset: {
      if (GetArena() == nullptr) {
        delete _impl_.update_.reset_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.update_.reset_);
      }
      break;
    }
    case kStep: {
      if (GetArena() == nullptr) {
        delete _impl_.update_.step_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.update_.step_);
      }
      break;
    }
    case UPDATE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = UPDATE_NOT_SET;
}


inline void* PROTOBUF_NONNULL StateUpdate::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) StateUpdate(arena);
}
constexpr auto StateUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StateUpdate),
                                            alignof(StateUpdate));
}
constexpr auto StateUpdate::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_StateUpdate_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &StateUpdate::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<StateUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &StateUpdate::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<StateUpdate>(), &StateUpdate::ByteSizeLong,
              &StateUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_._cached_size_),
          false,
      },
      &StateUpdate::kDescriptorMethods,
      &descriptor_table_StateUpdates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull StateUpdate_class_data_ =
        StateUpdate::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
StateUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&StateUpdate_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(StateUpdate_class_data_.tc_table);
  return StateUpdate_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2>
StateUpdate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_._has_bits_),
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    StateUpdate_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Schola::StateUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Schola.CommunicatorStatus status = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateUpdate, _impl_.status_), 0>(),
     {24, 0, 0, PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Schola.Reset reset = 1;
    {PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_.update_.reset_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Schola.Step step = 2;
    {PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_.update_.step_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Schola.CommunicatorStatus status = 3;
    {PROTOBUF_FIELD_OFFSET(StateUpdate, _impl_.status_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Schola::Reset>()},
      {::_pbi::TcParser::GetTable<::Schola::Step>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void StateUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.StateUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  clear_update();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL StateUpdate::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const StateUpdate& this_ = static_cast<const StateUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL StateUpdate::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const StateUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Schola.StateUpdate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.update_case()) {
    case kReset: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.update_.reset_, this_._impl_.update_.reset_->GetCachedSize(), target,
          stream);
      break;
    }
    case kStep: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.update_.step_, this_._impl_.update_.step_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  // .Schola.CommunicatorStatus status = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.StateUpdate)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t StateUpdate::ByteSizeLong(const MessageLite& base) {
  const StateUpdate& this_ = static_cast<const StateUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t StateUpdate::ByteSizeLong() const {
  const StateUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Schola.StateUpdate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .Schola.CommunicatorStatus status = 3;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  switch (this_.update_case()) {
    // .Schola.Reset reset = 1;
    case kReset: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.update_.reset_);
      break;
    }
    // .Schola.Step step = 2;
    case kStep: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.update_.step_);
      break;
    }
    case UPDATE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void StateUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StateUpdate*>(&to_msg);
  auto& from = static_cast<const StateUpdate&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.StateUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_status() != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_update();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kReset: {
        if (oneof_needs_init) {
          _this->_impl_.update_.reset_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.update_.reset_);
        } else {
          _this->_impl_.update_.reset_->MergeFrom(*from._impl_.update_.reset_);
        }
        break;
      }
      case kStep: {
        if (oneof_needs_init) {
          _this->_impl_.update_.step_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.update_.step_);
        } else {
          _this->_impl_.update_.step_->MergeFrom(*from._impl_.update_.step_);
        }
        break;
      }
      case UPDATE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StateUpdate::CopyFrom(const StateUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.StateUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StateUpdate::InternalSwap(StateUpdate* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.status_, other->_impl_.status_);
  swap(_impl_.update_, other->_impl_.update_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata StateUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_StateUpdates_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
#include "ScholaProtobufMacroGuardEnd.h"
THIRD_PARTY_INCLUDES_END
